from Basic import *
from Classic import *
from Shadows import *
from Uldum import *
from Dragons import *
from Galakrond import *
from DemonHunterInitiate import *
from Outlands import *
cardPool = {
			"Basic~Neutral~Spell~0~The Coin~Uncollectible": TheCoin,
			"Basic~Neutral~Minion~1~1~1~None~Elven Archer~Battlecry": ElvenArcher,
			"Basic~Neutral~Minion~1~1~2~None~Goldshire Footman~Taunt": GoldshireFootman,
			"Basic~Neutral~Minion~1~1~1~Murloc~Grimscale Oracle": GrimscaleOracle,
			"Basic~Neutral~Minion~1~2~1~Murloc~Murloc Raider": MurlocRaider,
			"Basic~Neutral~Minion~1~1~1~Beast~Stonetusk Boar~Charge": StonetuskBoar,
			"Basic~Neutral~Minion~1~2~1~None~Voodoo Doctor~Battlecry": VoodooDoctor,
			"Basic~Paladin~Minion~1~1~1~None~Silver Hand Recruit~Uncollectible": SilverHandRecruit,
			"Basic~Shaman~Minion~1~1~1~Totem~Searing Totem~Uncollectible": SearingTotem,
			"Basic~Shaman~Minion~1~0~2~Totem~Stoneclaw Totem~Taunt~Uncollectible": StoneclawTotem,
			"Basic~Shaman~Minion~1~0~2~Totem~Healing Totem~Uncollectible": HealingTotem,
			"Basic~Shaman~Minion~1~0~2~Totem~Wrath of Air Totem~Spell Damage~Uncollectible": WrathofAirTotem,
			"Basic~Neutral~Minion~2~3~2~None~Acidic Swamp Ooze~Battlecry": AcidicSwampOoze,
			"Basic~Neutral~Minion~2~3~2~Beast~Bloodfen Raptor": BloodfenRaptor,
			"Basic~Neutral~Minion~2~2~1~Murloc~Bluegill Warrior~Charge": BluegillWarrior,
			"Basic~Neutral~Minion~2~2~2~None~Frostwolf Grunt~Taunt": FrostwolfGrunt,
			"Basic~Neutral~Minion~2~2~2~None~Kobold Geomancer~Spell Damage": KoboldGeomancer,
			"Basic~Neutral~Minion~2~2~1~Murloc~Murloc Tidehunter~Battlecry": MurlocTidehunter,
			"Basic~Neutral~Minion~1~1~1~Murloc~Murloc Scout~Uncollectible": MurlocScout,
			"Basic~Neutral~Minion~2~1~1~None~Novice Engineer~Battlecry": NoviceEngineer,
			"Basic~Neutral~Minion~2~2~3~Beast~River Crocolisk": RiverCrocolisk,
			"Basic~Neutral~Minion~3~1~4~None~Dalaran Mage~Spell Damage": DalaranMage,
			"Basic~Neutral~Minion~3~2~2~None~Ironforge Rifleman~Battlecry": IronforgeRifleman,
			"Basic~Neutral~Minion~3~3~3~Beast~Ironfur Grizzly~Taunt": IronfurGrizzly,
			"Basic~Neutral~Minion~3~5~1~Elemental~Magma Rager": MagmaRager,
			"Basic~Neutral~Minion~3~2~2~None~Raid Leader": RaidLeader,
			"Basic~Neutral~Minion~3~2~3~None~Razorfen Hunter~Battlecry": RazorfenHunter,
			"Basic~Neutral~Minion~1~1~1~Beast~Boar~Uncollectible": Boar,
			"Basic~Neutral~Minion~3~3~2~None~Shattered Sun Cleric~Battlecry": ShatteredSunCleric,
			"Basic~Neutral~Minion~3~1~4~Beast~Silverback Patriarch~Taunt": SilverbackPatriarch,
			"Basic~Neutral~Minion~3~3~1~None~Wolfrider~Charge": Wolfrider,
			"Basic~Neutral~Minion~4~4~5~None~Chillwind Yeti": ChillwindYeti,
			"Basic~Neutral~Minion~4~2~4~None~Dragonling Mechanic~Battlecry": DragonlingMechanic,
			"Basic~Neutral~Minion~1~2~1~Mech~Mechanical Dragonling~Uncollectible": MechanicalDragonling,
			"Basic~Neutral~Minion~4~2~4~None~Gnomish Inventor~Battlecry": GnomishInventor,
			"Basic~Neutral~Minion~4~2~7~Beast~Oasis Snapjaw": OasisSnapjaw,
			"Basic~Neutral~Minion~4~4~4~None~Ogre Magi~Spell Damage": OgreMagi,
			"Basic~Neutral~Minion~4~3~5~None~Sen'jin Shieldmasta~Taunt": SenjinShieldmasta,
			"Basic~Neutral~Minion~4~2~5~None~Stormwind Knight~Charge": StormwindKnight,
			"Basic~Neutral~Minion~5~5~4~None~Booty Bay Bodyguard~Taunt": BootyBayBodyguard,
			"Basic~Neutral~Minion~5~4~5~None~Darkscale Healer~Battlecry": DarkscaleHealer,
			"Basic~Neutral~Minion~5~4~4~None~Frostwolf Warlord~Battlecry": FrostwolfWarlord,
			"Basic~Neutral~Minion~5~2~7~None~Gurubashi Berserker": GurubashiBerserker,
			"Basic~Neutral~Minion~5~4~4~None~Nightblade~Battlecry": Nightblade,
			"Basic~Neutral~Minion~5~4~2~None~Stormpike Commando~Battlecry": StormpikeCommando,
			"Basic~Neutral~Minion~6~6~5~None~Lord of the Arena~Taunt": LordoftheArena,
			"Basic~Neutral~Minion~6~4~7~None~Archmage~Spell Damage": Archmage,
			"Basic~Neutral~Minion~6~6~7~None~Boulderfist Ogre": BoulderfistOgre,
			"Basic~Neutral~Minion~6~5~2~None~Reckless Rocketeer~Charge": RecklessRocketeer,
			"Basic~Neutral~Minion~7~9~5~Beast~Core Hound": CoreHound,
			"Basic~Neutral~Minion~7~6~6~None~Stormwind Champion": StormwindChampion,
			"Basic~Neutral~Minion~7~7~7~None~War Golem": WarGolem,
			"Basic~Demon Hunter~Minion~1~2~1~Demon~Shadowhoof Slayer~Battlecry": ShadowhoofSlayer,
			"Basic~Demon Hunter~Spell~2~Chaos Strike": ChaosStrike,
			"Basic~Demon Hunter~Minion~2~3~2~Demon~Sightless Watcher~Battlecry": SightlessWatcher,
			"Basic~Demon Hunter~Weapon~3~2~2~Aldrachi Warblades~Lifesteal": AldrachiWarblades,
			"Basic~Demon Hunter~Spell~3~Coordinated Strike": CoordinatedStrike,
			"Basic~Demon Hunter~Minion~1~1~1~None~Illidari~Uncollectible": IllidariInitiate,
			"Basic~Demon Hunter~Minion~3~4~2~Demon~Satyr Overseer": SatyrOverseer,
			"Basic~Demon Hunter~Minion~2~2~2~Demon~Illidari Satyr~Uncollectible": IllidariSatyr,
			"Basic~Demon Hunter~Spell~3~Soul Cleave": SoulCleave,
			"Basic~Demon Hunter~Spell~5~Chaos Nova": ChaosNova,
			"Basic~Demon Hunter~Minion~5~7~4~None~Glaivebound Adept~Battlecry": GlaiveboundAdept,
			"Basic~Demon Hunter~Spell~8~Inner Demon": InnerDemon,
			"Basic~Druid~Spell~0~Innervate": Innervate,
			"Basic~Druid~Spell~0~Moonfire": Moonfire,
			"Basic~Druid~Spell~1~Claw": Claw,
			"Basic~Druid~Spell~2~Mark of the Wild": MarkoftheWild,
			"Basic~Druid~Spell~3~Healing Touch": HealingTouch,
			"Basic~Druid~Spell~3~Savage Roar": SavageRoar,
			"Basic~Druid~Spell~3~Wild Growth": WildGrowth,
			"Basic~Druid~Spell~0~Excess Mana~Uncollectible": ExcessMana,
			"Basic~Druid~Spell~4~Swipe": Swipe,
			"Basic~Druid~Spell~6~Starfire": Starfire,
			"Basic~Druid~Minion~8~8~8~None~Ironbark Protector~Taunt": IronbarkProtector,
			"Basic~Hunter~Spell~1~Arcane Shot": ArcaneShot,
			"Basic~Hunter~Minion~1~1~1~Beast~Timber Wolf": TimberWolf,
			"Basic~Hunter~Spell~1~Tracking": Tracking,
			"Basic~Hunter~Spell~2~Hunter's Mark": HuntersMark,
			"Basic~Hunter~Spell~3~Animal Companion": AnimalCompanion,
			"Basic~Hunter~Minion~3~4~2~Beast~Huffer~Charge~Uncollectible": Huffer,
			"Basic~Hunter~Minion~3~2~4~Beast~Leokk~Uncollectible": Leokk,
			"Basic~Hunter~Minion~3~4~4~Beast~Misha~Taunt~Uncollectible": Misha,
			"Basic~Hunter~Spell~3~Kill Command": KillCommand,
			"Basic~Hunter~Minion~4~4~3~None~Houndmaster~Battlecry": Houndmaster,
			"Basic~Hunter~Spell~4~Multi Shot": MultiShot,
			"Basic~Hunter~Minion~5~3~2~Beast~Starving Buzzard": StarvingBuzzard,
			"Basic~Hunter~Minion~5~2~5~Beast~Tundra Rhino": TundraRhino,
			"Basic~Mage~Spell~1~Arcane Missiles": ArcaneMissiles,
			"Basic~Mage~Spell~1~Mirror Image": MirrorImage,
			"Basic~Mage~Minion~1~0~2~None~Mirror Image~Taunt~Uncollectible": MirrorImage_Minion,
			"Basic~Mage~Spell~2~Arcane Explosion": ArcaneExplosion,
			"Basic~Mage~Spell~2~Frostbolt": Frostbolt,
			"Basic~Mage~Spell~3~Arcane Intellect": ArcaneIntellect,
			"Basic~Mage~Spell~3~Frost Nova": FrostNova,
			"Basic~Mage~Spell~4~Fireball": Fireball,
			"Basic~Mage~Spell~4~Polymorph": Polymorph,
			"Basic~Neutral~Minion~1~1~1~Beast~Sheep~Uncollectible": Sheep,
			"Basic~Mage~Minion~4~3~6~Elemental~Water Elemental": WaterElemental,
			"Basic~Mage~Spell~7~Flamestrike": Flamestrike,
			"Basic~Monk~Spell~0~Resuscitate": Resuscitate,
			"Basic~Monk~Minion~1~0~2~None~Arch of the Temple~Taunt~Battlecry": ArchoftheTemple,
			"Basic~Monk~Minion~1~1~1~None~Monk Attacker~Rush~Uncollectible": MonkAttacker,
			"Basic~Monk~Weapon~1~0~4~Cane with a Wine Gourd": CanewithaWineGourd,
			"Basic~Monk~Minion~1~1~3~None~Monk's Apprentice": MonksApprentice,
			"Basic~Monk~Spell~1~Shaohao's Protection": ShaohaosProtection,
			"Basic~Monk~Spell~2~Effusive Mists": EffusiveMists,
			"Basic~Monk~Minion~2~1~4~None~Swift Brewmaster": SwiftBrewmaster,
			"Basic~Monk~Spell~3~Provoke": Provoke,
			"Basic~Monk~Minion~3~1~4~None~Sweeping Kick Fighter~Rush": SweepingKickFighter,
			"Basic~Monk~Minion~3~3~4~None~Shado-Pan Wu Kao": ShadoPanWuKao,
			"Basic~Paladin~Spell~1~Blessing of Might": BlessingofMight,
			"Basic~Paladin~Spell~1~Hand of Protection": HandofProtection,
			"Basic~Paladin~Spell~1~Humility": Humility,
			"Basic~Paladin~Weapon~1~1~4~Light's Justice": LightsJustice,
			"Basic~Paladin~Spell~2~Holy Light": HolyLight,
			"Basic~Paladin~Spell~4~Blessing of Kings": BlessingofKings,
			"Basic~Paladin~Spell~4~Consecration": Consecration,
			"Basic~Paladin~Spell~4~Hammer of Wrath": HammerofWrath,
			"Basic~Paladin~Weapon~4~4~2~Truesilver Champion": TruesilverChampion,
			"Basic~Paladin~Minion~7~5~6~None~Guardian of Kings~Battlecry": GuardianofKings,
			"Basic~Priest~Spell~0~Power Word: Shield": PowerWordShield,
			"Basic~Priest~Spell~1~Holy Smite": HolySmite,
			"Basic~Priest~Spell~1~Mind Vision": MindVision,
			"Basic~Priest~Minion~1~1~1~None~Psychic Conjurer-Battlecry": PsychicConjurer,
			"Basic~Priest~Spell~1~Radiance": Radiance,
			"Basic~Priest~Spell~2~Shadow Word: Death": ShadowWordDeath,
			"Basic~Priest~Spell~2~Shadow Word: Pain": ShadowWordPain,
			"Basic~Priest~Spell~4~Holy Nova": HolyNova,
			"Basic~Priest~Spell~4~Power Infusion": PowerInfusion,
			"Basic~Priest~Spell~10~Mind Control": MindControl,
			"Basic~Rogue~Spell~0~Backstab": Backstab,
			"Basic~Rogue~Weapon~1~1~2~Wicked Knife~Uncollectible": WickedKnife,
			"Basic~Rogue~Weapon~1~2~2~Poisoned Dagger~Uncollectible": PoisonedDagger,
			"Basic~Rogue~Spell~1~Deadly Poison": DeadlyPoison,
			"Basic~Rogue~Spell~1~Sinister Strike": SinisterStrike,
			"Basic~Rogue~Spell~2~Sap": Sap,
			"Basic~Rogue~Spell~2~Shiv": Shiv,
			"Basic~Rogue~Spell~3~Fan of Knives": FanofKnives,
			"Basic~Rogue~Minion~4~3~3~None~Plaguebringer~Battlecry": Plaguebringer,
			"Basic~Rogue~Spell~5~Assassinate": Assassinate,
			"Basic~Rogue~Weapon~5~3~4~Assassin's Blade": AssassinsBlade,
			"Basic~Rogue~Spell~7~Sprint": Sprint,
			"Basic~Shaman~Spell~0~Ancestral Healing": AncestralHealing,
			"Basic~Shaman~Spell~0~Totemic Might": TotemicMight,
			"Basic~Shaman~Spell~1~Frost Shock": FrostShock,
			"Basic~Shaman~Spell~2~Rockbiter Weapon": RockbiterWeapon,
			"Basic~Shaman~Spell~2~Windfury": Windfury,
			"Basic~Shaman~Minion~3~0~3~Totem~Flametongue Totem": FlametongueTotem,
			"Basic~Shaman~Spell~4~Hex": Hex,
			"Basic~Neutral~Minion~1~0~1~Beast~Frog~Taunt~Uncollectible": Frog,
			"Basic~Shaman~Minion~4~3~3~None~Windspeaker~Battlecry": Windspeaker,
			"Basic~Shaman~Spell~5~Bloodlust": Bloodlust,
			"Basic~Shaman~Minion~6~6~5~Elemental~Fire Elemental~Battlecry": FireElemental,
			"Basic~Warlock~Spell~0~Sacrificial Pact": SacrificialPact,
			"Basic~Warlock~Spell~1~Corruption": Corruption,
			"Basic~Warlock~Spell~1~Mortal Coil": MortalCoil,
			"Basic~Warlock~Spell~1~Soulfire": Soulfire,
			"Basic~Warlock~Minion~1~1~3~Demon~Voidwalker~Taunt": Voidwalker,
			"Basic~Warlock~Minion~2~4~3~Demon~Felstalker~Battlecry": Felstalker,
			"Basic~Warlock~Spell~3~Drain Life": DrainLife,
			"Basic~Warlock~Spell~3~Shadow Bolt": ShadowBolt,
			"Basic~Warlock~Spell~4~Hellfire": Hellfire,
			"Basic~Warlock~Minion~6~6~6~Demon~Dread Infernal~Battlecry": DreadInfernal,
			"Basic~Warrior~Spell~1~Whirlwind": Whirlwind,
			"Basic~Warrior~Spell~1~Charge": Charge,
			"Basic~Warrior~Spell~2~Execute": Execute,
			"Basic~Warrior~Spell~2~Cleave": Cleave,
			"Basic~Warrior~Spell~2~Heroic Strike": HeroicStrike,
			"Basic~Warrior~Weapon~3~3~2~Fiery War Axe": FieryWarAxe,
			"Basic~Warrior~Spell~3~Shield Block": ShieldBlock,
			"Basic~Warrior~Minion~3~2~3~None~Warsong Commander": WarsongCommander,
			"Basic~Warrior~Minion~4~4~3~None~Kor'kron Elite~Charge": KorkronElite,
			"Basic~Warrior~Weapon~5~5~2~Arcanite Reaper": ArcaniteReaper,
			"Classic~Neutral~Minion~0~1~1~None~Wisp": Wisp,
			"Classic~Neutral~Minion~1~1~1~None~Abusive Sergeant~Battlecry": AbusiveSergeant,
			"Classic~Neutral~Minion~1~1~1~None~Argent Squire~Divine Shield": ArgentSquire,
			"Classic~Neutral~Minion~1~1~1~Beast~Angry Chicken": AngryChicken,
			"Classic~Neutral~Minion~1~1~2~Pirate~Bloodsail Corsair~Battlecry": BloodsailCorsair,
			"Classic~Neutral~Minion~1~1~2~Beast~Hungry Crab~Battlecry": HungryCrab,
			"Classic~Neutral~Minion~1~1~1~None~Leper Gnome~Deathrattle": LeperGnome,
			"Classic~Neutral~Minion~1~1~2~None~Lightwarden": Lightwarden,
			"Classic~Neutral~Minion~1~1~2~Murloc~Murloc Tidecaller": MurlocTidecaller,
			"Classic~Neutral~Minion~1~1~2~None~Secretkeeper": Secretkeeper,
			"Classic~Neutral~Minion~1~0~4~None~Shieldbearer~Taunt": Shieldbearer,
			"Classic~Neutral~Minion~1~2~1~Pirate~Southsea Deckhand": SouthseaDeckhand,
			"Classic~Neutral~Minion~1~2~1~None~Worgen Infiltrator~Stealth": WorgenInfiltrator,
			"Classic~Neutral~Minion~1~1~1~Beast~Young Dragonhawk~Windfury": YoungDragonhawk,
			"Classic~Neutral~Minion~1~2~1~None~Young Priestess": YoungPriestess,
			"Classic~Neutral~Minion~2~2~3~None~Amani Berserker": AmaniBerserker,
			"Classic~Neutral~Minion~2~4~5~None~Ancient Watcher": AncientWatcher,
			"Classic~Neutral~Minion~2~1~1~None~Bloodmage Thalnos~Deathrattle~Spell Damage~Legendary": BloodmageThalnos,
			"Classic~Neutral~Minion~2~2~3~Pirate~Bloodsail Raider~Battlecry": BloodsailRaider,
			"Classic~Neutral~Minion~2~2~2~None~Crazed Alchemist~Battlecry": CrazedAlchemist,
			"Classic~Neutral~Minion~2~2~2~Beast~Dire Wolf Alpha": DireWolfAlpha,
			"Classic~Neutral~Minion~2~0~7~None~Doomsayer": Doomsayer,
			"Classic~Neutral~Minion~2~3~2~Dragon~Faerie Dragon": FaerieDragon,
			"Classic~Neutral~Minion~2~2~2~None~Knife Juggler": KnifeJuggler,
			"Classic~Neutral~Minion~2~2~1~None~Loot Hoarder~Deathrattle": LootHoarder,
			"Classic~Neutral~Minion~2~0~4~None~Lorewalker Cho~Legendary": LorewalkerCho,
			"Classic~Neutral~Minion~2~3~2~None~Mad Bomber~Battlecry": MadBomber,
			"Classic~Neutral~Minion~2~1~3~None~Mana Addict": ManaAddict,
			"Classic~Neutral~Minion~2~2~2~None~Mana Wraith": ManaWraith,
			"Classic~Neutral~Minion~2~1~3~None~Master Swordsmith": MasterSwordsmith,
			"Classic~Neutral~Minion~2~4~4~None~Millhouse Manastorm~Battlecry~Legendary": MillhouseManastorm,
			"Classic~Neutral~Minion~2~0~4~None~Nat Pagle~Legendary": NatPagle,
			"Classic~Neutral~Minion~2~2~2~None~Pint-Sized Summoner": PintSizedSummoner,
			"Classic~Neutral~Minion~2~2~3~None~Sunfury Protector~Battlecry": SunfuryProtector,
			"Classic~Neutral~Minion~2~3~2~None~Wild Pyromancer": WildPyromancer,
			"Classic~Neutral~Minion~2~3~2~None~Youthful Brewmaster~Battlecry": YouthfulBrewmaster,
			"Classic~Neutral~Minion~3~0~3~Mech~Alarm-o-Bot": AlarmoBot,
			"Classic~Neutral~Minion~3~4~4~None~Arcane Golem~Battlecry": ArcaneGolem,
			"Classic~Neutral~Minion~3~3~3~None~Blood Knight~Battlecry": BloodKnight,
			"Classic~Neutral~Minion~3~3~2~Dragon~Brightwing~Battlecry~Legendary": Brightwing,
			"Classic~Neutral~Minion~3~2~3~Murloc~Coldlight Seer~Battlecry": ColdlightSeer,
			"Classic~Neutral~Minion~3~1~4~Mech~Demolisher": Demolisher,
			"Classic~Neutral~Minion~3~3~3~None~Earthen Ring Farseer~Battlecry": EarthenRingFarseer,
			"Classic~Neutral~Minion~3~2~3~Beast~Emperor Cobra~Poisonous": EmperorCobra,
			"Classic~Neutral~Minion~3~2~3~None~Flesheating Ghoul": FlesheatingGhoul,
			"Classic~Neutral~Minion~3~2~3~Mech~Harvest Golem~Deathrattle": HarvestGolem,
			"Classic~Neutral~Minion~1~2~1~Mech~Damaged Golem~Uncollectible": DamagedGolem,
			"Classic~Neutral~Minion~3~1~5~None~Imp Master": ImpMaster,
			"Classic~Neutral~Minion~1~1~1~Demon~Imp~Uncollectible": Imp,
			"Classic~Neutral~Minion~3~4~7~None~Injured Blademaster~Battlecry": InjuredBlademaster,
			"Classic~Neutral~Minion~3~2~1~Beast~Ironbeak Owl~Battlecry": IronbeakOwl,
			"Classic~Neutral~Minion~3~4~2~Beast~Jungle Panther~Stealth": JunglePanther,
			"Classic~Neutral~Minion~3~5~5~Beast~King Mukla~Battlecry~Legendary": KingMukla,
			"Classic~Neutral~Spell~1~Bananas~Uncollectible": Bananas,
			"Classic~Neutral~Minion~3~3~3~Murloc~Murloc Warleader": MurlocWarleader,
			"Classic~Neutral~Minion~3~2~2~None~Questing Adventurer": QuestingAdventurer,
			"Classic~Neutral~Minion~3~3~3~None~Raging Worgen": RagingWorgen,
			"Classic~Neutral~Minion~3~3~1~None~Scarlet Crusader~Divine Shield": ScarletCrusader,
			"Classic~Neutral~Minion~3~3~3~Pirate~Southsea Captain": SouthseaCaptain,
			"Classic~Neutral~Minion~3~2~3~None~Tauren Warrior~Taunt": TaurenWarrior,
			"Classic~Neutral~Minion~3~2~3~None~Thrallmar Farseer~Windfury": ThrallmarFarseer,
			"Classic~Neutral~Minion~3~3~3~None~Tinkmaster Overspark~Battlecry~Legendary": TinkmasterOverspark,
			"Classic~Neutral~Minion~5~5~5~Beast~Devilsaur~Uncollectible": Devilsaur,
			"Classic~Neutral~Minion~1~1~1~Beast~Squirrel~Uncollectible": Squirrel,
			"Classic~Neutral~Minion~4~5~4~None~Ancient Brewmaster~Battlecry": AncientBrewmaster,
			"Classic~Neutral~Minion~4~2~5~None~Ancient Mage~Battlecry": AncientMage,
			"Classic~Neutral~Minion~4~4~2~None~Cult Master": CultMaster,
			"Classic~Neutral~Minion~4~4~4~None~Dark Iron Dwarf~Battlecry": DarkIronDwarf,
			"Classic~Neutral~Minion~4~2~3~None~Defender of Argus~Battlecry": DefenderofArgus,
			"Classic~Neutral~Minion~4~3~3~Pirate~Dread Corsair~Taunt": DreadCorsair,
			"Classic~Neutral~Minion~4~1~7~None~Mogu'shan Warden~Taunt": MogushanWarden,
			"Classic~Neutral~Minion~4~3~3~None~Silvermoon Guardian~Divine Shield": SilvermoonGuardian,
			"Classic~Neutral~Minion~4~5~4~None~SI:7 Infiltrator~Battlecry": SI7Infiltrator,
			"Classic~Neutral~Minion~4~4~1~Dragon~Twilight Drake~Battlecry": TwilightDrake,
			"Classic~Neutral~Minion~4~3~5~None~Violet Teacher": VioletTeacher,
			"Classic~Neutral~Minion~1~1~1~None~Violet Apprentice~Uncollectible": VioletApprentice,
			"Classic~Neutral~Minion~5~4~4~None~Abomination~Taunt~Deathrattle": Abomination,
			"Classic~Neutral~Minion~5~4~2~None~Big Game Hunter~Battlecry": BigGameHunter,
			"Classic~Neutral~Minion~5~5~4~Pirate~Captain Greenskin~Battlecry~Legendary": CaptainGreenskin,
			"Classic~Neutral~Minion~5~3~3~None~Faceless Manipulator~Battlecry": FacelessManipulator,
			"Classic~Neutral~Minion~5~3~6~None~Fen Creeper~Taunt": FenCreeper,
			"Classic~Neutral~Minion~5~5~4~None~Harrison Jones~Battlecry~Legendary": HarrisonJones,
			"Classic~Neutral~Minion~5~4~4~None~Silver Hand Knight~Battlecry": SilverHandKnight,
			"Classic~Neutral~Minion~2~2~2~None~Squire~Uncollectible": Squire,
			"Classic~Neutral~Minion~5~4~6~None~Spiteful Smith": SpitefulSmith,
			"Classic~Neutral~Minion~5~3~5~Beast~Stampeding Kodo~Battlecry": StampedingKodo,
			"Classic~Neutral~Minion~5~5~5~Beast~Stranglethorn Tiger~Stealth": StranglethornTiger,
			"Classic~Neutral~Minion~5~7~6~None~Venture Co. Mercenary": VentureCoMercenary,
			"Classic~Neutral~Minion~6~4~2~None~Argent Commander~Divine Shield~Charge": ArgentCommander,
			"Classic~Neutral~Minion~6~4~5~None~Cairne Bloodhoof~Deathrattle~Legendary": CairneBloodhoof,
			"Classic~Neutral~Minion~6~4~5~None~Baine Bloodhoof~Uncollectible~Legendary": BaineBloodhoof,
			"Classic~Neutral~Minion~6~5~5~Elemental~Frost Elemental~Battlecry": FrostElemental,
			"Classic~Neutral~Minion~6~4~4~None~Gadgetzan Auctioneer": GadgetzanAuctioneer,
			"Classic~Neutral~Minion~6~4~4~None~Hogger~Legendary": Hogger,
			"Classic~Neutral~Minion~2~2~2~None~Gnoll~Taunt~Uncollectible": Gnoll,
			"Classic~Neutral~Minion~6~7~5~Demon~Illidan Stormrage~Legendary": Xavius,
			"Classic~Neutral~Minion~1~2~1~Elemental~Xavian Satyr~Uncollectible": XavianSatyr,
			"Classic~Neutral~Minion~6~5~4~None~Priestess of Elune~Battlecry": PriestessofElune,
			"Classic~Neutral~Minion~6~4~5~None~Sunwalker~Divine Shield~Taunt": Sunwalker,
			"Classic~Neutral~Minion~6~9~7~Beast~The Beast~Deathrattle~Legendary": TheBeast,
			"Classic~Neutral~Minion~3~3~3~None~Finkle Einhorn~Uncollectible~Legendary": FinkleEinhorn,
			"Classic~Neutral~Minion~6~4~5~None~The Black Knight~Battlecry~Legendary": TheBlackKnight,
			"Classic~Neutral~Minion~6~4~5~None~Windfury Harpy~Windfury": WindfuryHarpy,
			"Classic~Neutral~Minion~7~4~4~None~Barrens Stablehand~Battlecry": BarrensStablehand,
			"Classic~Neutral~Minion~7~7~5~Elemental~Baron Geddon~Legendary": BaronGeddon,
			"Classic~Neutral~Minion~7~6~8~None~High Inquisitor Whitemane~Battlecry~Legendary": HighInquisitorWhitemane,
			"Classic~Neutral~Minion~7~7~5~None~Ravenholdt Assassin~Stealth": RavenholdtAssassin,
			"Classic~Neutral~Minion~8~5~5~Elemental~Arcane Devourer": ArcaneDevourer,
			"Classic~Neutral~Minion~8~7~7~None~Gruul~Legendary": Gruul,
			"Classic~Neutral~Minion~9~8~8~Dragon~Alexstrasza~Battlecry~Legendary": Alexstrasza,
			"Classic~Neutral~Minion~9~4~12~Dragon~Malygos~Spell Damage~Legendary": Malygos,
			"Classic~Neutral~Minion~9~8~8~Dragon~Nozdormu~Legendary": Nozdormu,
			"Classic~Neutral~Minion~9~8~8~Dragon~Onyxia~Battlecry~Legendary": Onyxia,
			"Classic~Neutral~Minion~1~1~1~Dragon~Whelp~Uncollectible": Whelp,
			"Classic~Neutral~Minion~9~4~12~Dragon~Ysera~Legendary": Ysera,
			"Classic~DreamCard~Spell~0~Dream~Uncollectible": Dream,
			"Classic~DreamCard~Spell~0~Nightmare~Uncollectible": Nightmare,
			"Classic~DreamCard~Spell~2~Ysera Awakens~Uncollectible": YseraAwakens,
			"Classic~DreamCard~Minion~3~3~5~None~Laughing Sister~Uncollectible": LaughingSister,
			"Classic~DreamCard~Minion~4~7~6~Dragon~Emerald Drake~Uncollectible": EmeraldDrake,
			"Classic~Neutral~Minion~10~12~12~Dragon~Deathwing~Battlecry~Legendary": Deathwing,
			"Classic~Neutral~Minion~10~8~8~None~Sea Giant": SeaGiant,
			"Classic~Druid~Spell~1~Savagery": Savagery,
			"Classic~Druid~Spell~2~Power of the Wild~Choose One": PoweroftheWild,
			"Classic~Druid~Spell~2~Leader of the Pack~Uncollectible": LeaderofthePack,
			"Classic~Druid~Spell~2~Summon a Panther~Uncollectible": SummonaPanther,
			"Classic~Druid~Minion~2~3~2~Beast~Panther~Uncollectible": Panther,
			"Classic~Druid~Spell~2~Wrath~Choose One": Wrath,
			"Classic~Druid~Spell~2~Solar Wrath~Uncollectible": SolarWrath,
			"Classic~Druid~Spell~2~Nature's Wrath~Uncollectible": NaturesWrath,
			"Classic~Druid~Spell~3~Mark of Nature~Choose One": MarkofNature,
			"Classic~Druid~Spell~3~Tiger's Fury~Uncollectible": TigersFury,
			"Classic~Druid~Spell~3~Thick Hide~Uncollectible": ThickHide,
			"Classic~Druid~Spell~4~Bite": Bite,
			"Classic~Druid~Minion~4~2~2~None~Keeper of the Grove~Choose One": KeeperoftheGrove,
			"Classic~Druid~Spell~4~Soul of the Forest": SouloftheForest,
			"Classic~Druid~Minion~5~4~4~None~Druid of the Claw~Choose One": DruidoftheClaw,
			"Classic~Druid~Minion~5~4~4~Beast~Druid of the Claw~Charge~Uncollectible": DruidoftheClaw_Charge,
			"Classic~Druid~Minion~5~4~6~Beast~Druid of the Claw~Taunt~Uncollectible ": DruidoftheClaw_Taunt,
			"Classic~Druid~Minion~5~4~6~Beast~Druid of the Claw~Taunt~Charge~Uncollectible ": DruidoftheClaw_Both,
			"Classic~Druid~Spell~5~Force of Nature": ForceofNature,
			"Classic~Druid~Minion~2~2~2~None~Treant Classic~Uncollectible": Treant_Classic,
			"Classic~Druid~Spell~5~Starfall~Choose One": Starfall,
			"Classic~Druid~Spell~5~Starlord~Uncollectible": Starlord,
			"Classic~Druid~Spell~5~Stellar Drift~Uncollectible": StellarDrift,
			"Classic~Druid~Spell~6~Nourish~Choose One": Nourish,
			"Classic~Druid~Spell~6~Rampant Growth~Uncollectible": RampantGrowth,
			"Classic~Druid~Spell~6~Enrich~Uncollectible": Enrich,
			"Classic~Druid~Minion~7~5~5~None~Ancient of Lore~Choose One": AncientofLore,
			"Classic~Druid~Minion~7~5~5~None~Ancient of War~Choose One": AncientofWar,
			"Classic~Druid~Spell~8~Gift of the Wild": GiftoftheWild,
			"Classic~Druid~Minion~9~5~8~None~Cenarius~Choose One~Legendary": Cenarius,
			"Classic~Druid~Minion~2~2~2~None~Treant~Taunt~Uncollectible": Treant_Classic_Taunt,
			"Classic~Hunter~Spell~1~Bestial Wrath": BestialWrath,
			"Classic~Hunter~Spell~2~Explosive Trap~~Secret": ExplosiveTrap,
			"Classic~Hunter~Spell~2~Freezing Trap~~Secret": FreezingTrap,
			"Classic~Hunter~Spell~2~Misdirection~~Secret": Misdirection,
			"Classic~Hunter~Spell~2~Snake Trap~~Secret": SnakeTrap,
			"Classic~Hunter~Minion~1~1~1~Beast~Snake~Uncollectible": Snake,
			"Classic~Hunter~Spell~2~Snipe~~Secret": Snipe,
			"Classic~Hunter~Spell~2~Flare": Flare,
			"Classic~Hunter~Minion~2~2~2~Beast~Scavenging Hyena": ScavengingHyena,
			"Classic~Hunter~Spell~3~Deadly Shot": DeadlyShot,
			"Classic~Hunter~Weapon~3~3~2~Eaglehorn Bow": EaglehornBow,
			"Classic~Hunter~Spell~3~Unleash the Hounds": UnleashtheHounds,
			"Classic~Hunter~Minion~1~1~1~Beast~Hound~Charge~Uncollectible": Hound,
			"Classic~Hunter~Spell~5~Explosive Shot": ExplosiveShot,
			"Classic~Hunter~Minion~6~6~5~Beast~Savannah Highmane~Deathrattle": SavannahHighmane,
			"Classic~Hunter~Minion~2~2~2~Beast~Hyena~Uncollectible": Hyena_Classic,
			"Classic~Hunter~Weapon~7~5~2~Gladiator's Longbow": GladiatorsLongbow,
			"Classic~Hunter~Minion~9~8~8~Beast~King Krush~Charge~Legendary": KingKrush,
			"Classic~Mage~Spell~1~Tome of Intellect": TomeofIntellect,
			"Classic~Mage~Spell~2~Icicle": Icicle,
			"Classic~Mage~Minion~2~1~3~None~Mana Wyrm": ManaWyrm,
			"Classic~Mage~Minion~2~3~2~None~Sorcerer's Apprentice": SorcerersApprentice,
			"Classic~Mage~Spell~3~Counterspell~~Secret": Counterspell,
			"Classic~Mage~Spell~3~Ice Barrier~~Secret": IceBarrier,
			"Classic~Mage~Spell~3~Mirror Entity~~Secret": MirrorEntity,
			"Classic~Mage~Spell~3~Spellbender~~Secret": Spellbender,
			"Classic~Mage~Minion~1~1~3~None~Spellbender~Uncollectible": Spellbender_Minion,
			"Classic~Mage~Spell~3~Vaporize~~Secret": Vaporize,
			"Classic~Mage~Minion~3~4~3~None~Kirin Tor Mage~Battlecry": KirinTorMage,
			"Classic~Mage~Spell~4~Cone of Cold": ConeofCold,
			"Classic~Mage~Minion~4~3~3~None~Ethereal Arcanist": EtherealArcanist,
			"Classic~Mage~Spell~6~Blizzard": Blizzard,
			"Classic~Mage~Minion~7~5~7~None~Archmage Antonidas~Legendary": ArchmageAntonidas,
			"Classic~Mage~Spell~10~Pyroblast": Pyroblast,
			"Classic~Monk~Minion~1~0~4~None~Wise Lorewalker Cho~Battlecry~Legendary": WiseLorewalkerCho,
			"Classic~Monk~Minion~1~1~1~Beast~Xuen, the White Tiger~Rush~Legendary": XuentheWhiteTiger_Mutable_1,
			"Classic~Monk~Minion~2~2~3~None~Defense Technique Master~Taunt~Quaff": DefenseTechniqueMaster,
			"Classic~Monk~Spell~2~Transcendance": Transcendance,
			"Classic~Monk~Spell~2~Purifying Brew~Quaff": PurifyingBrew,
			"Classic~Monk~Spell~3~Liquor~Quaff": Liquor,
			"Classic~Monk~Spell~3~Stave Off": StaveOff,
			"Classic~Monk~Spell~3~Touch of Karma": TouchofKarma,
			"Classic~Monk~Spell~3~Spirit Tether": SpiritTether,
			"Classic~Monk~Minion~2~2~2~Beast~Tethered Golem~Taunt~Uncollectible": TetheredGolem,
			"Classic~Monk~Spell~4~Drunken Boxing": DrunkenBoxing,
			"Classic~Monk~Minion~4~5~4~Monk~Onima Actuary~Stealth": OnimaActuary,
			"Classic~Monk~Minion~5~3~5~Beast~Spawn of Xuen~Rush~Battlecry": SpawnofXuen,
			"Classic~Monk~Spell~5~Quick Sip~Quaff": QuickSip,
			"Classic~Monk~Minion~4~5~3~None~Pawn of Shaohao~Rush~Windfury": PawnofShaohao,
			"Classic~Monk~Minion~4~3~5~None~Shaohao, the Emperor~Battlecry~Legendary": ShaohaotheEmperor,
			"Classic~Monk~Spell~6~Inner Peace": InnerPeace,
			"Classic~Monk~Minion~6~3~7~None~Lotus Healer~Taunt": LotusHealer,
			"Classic~Monk~Spell~6~Rushing Jade Wind": RushingJadeWind,
			"Classic~Monk~Minion~7~7~7~None~Kun-Lai Summit Zen Alchemist": KunLaiSummitZenAlchemist,
			"Classic~Monk~Weapon~8~2~4~Fists of the Heavens~Windfury": FistsoftheHeavens,
			"Classic~Monk~Minion~8~6~10~None~Pandaria Guardian~Taunt~Quaff": PandariaGuardian,
			"Classic~Monk~Minion~9~4~12~None~Monk Dragon Keeper~Rush~Windfury~Quaff": MonkDragonKeeper,
			"Classic~Paladin~Spell~1~Blessing of Wisdom": BlessingofWisdom,
			"Classic~Paladin~Spell~1~Eye for an Eye~~Secret": EyeforanEye,
			"Classic~Paladin~Spell~1~Noble Sacrifice~~Secret": NobleSacrifice,
			"Classic~Paladin~Minion~1~2~1~None~Defender~Uncollectible": Defender,
			"Classic~Paladin~Spell~1~Redemption~~Secret": Redemption,
			"Classic~Paladin~Spell~1~Repentance~~Secret": Repentance,
			"Classic~Paladin~Minion~2~2~2~None~Argent Protector~Battlecry": ArgentProtector,
			"Classic~Paladin~Spell~4~Equality": Equality,
			"Classic~Paladin~Minion~3~3~3~None~Ardor Peacekeeper~Battlecry": AldorPeacekeeper,
			"Classic~Paladin~Weapon~3~1~5~Sword of Justice": SwordofJustice,
			"Classic~Paladin~Spell~5~Blessed Champion": BlessedChampion,
			"Classic~Paladin~Spell~5~Holy Wrath": HolyWrath,
			"Classic~Paladin~Spell~5~Righteousness": Righteousness,
			"Classic~Paladin~Spell~6~Avenging Wrath": AvengingWrath,
			"Classic~Paladin~Spell~8~Lay on Hands": LayonHands,
			"Classic~Paladin~Minion~8~6~6~None~Tirion Fordring~Taunt~Divine Shield~Deathrattle~Legendary": TirionFordring,
			"Classic~Paladin~Weapon~5~5~3~Ashbringer~Uncollectible~Legendary": Ashbringer,
			"Classic~Priest~Spell~0~Circle of Healing": CircleofHealing,
			"Classic~Priest~Spell~0~Silence": Silence,
			"Classic~Priest~Spell~1~Inner Fire": InnerFire,
			"Classic~Priest~Minion~1~2~1~None~Scarlet Subjugator~Battlecry": ScarletSubjugator,
			"Classic~Priest~Minion~2~2~3~None~Kul Tiran Chaplain~Battlecry": KulTiranChaplain,
			"Classic~Priest~Minion~2~0~5~None~Lightwell": Lightwell,
			"Classic~Priest~Spell~2~Thoughtsteal": Thoughtsteal,
			"Classic~Priest~Spell~3~Shadow Madness": ShadowMadness,
			"Classic~Priest~Minion~4~0~5~None~Lightspawn": Lightspawn,
			"Classic~Priest~Spell~4~Mass Dispel": MassDispel,
			"Classic~Priest~Spell~4~Mindgames": Mindgames,
			"Classic~Priest~Spell~4~Shadow Word: Ruin": ShadowWordRuin,
			"Classic~Priest~Minion~1~0~1~None~Shadow of Nothing~Uncollectible": ShadowofNothing,
			"Classic~Priest~Minion~6~4~5~None~Cabal Shadow Priest~Battlecry": CabalShadowPriest,
			"Classic~Priest~Minion~5~5~6~None~Temple Enforcer~Battlecry": TempleEnforcer,
			"Classic~Priest~Minion~8~8~1~None~Natalie Seline~Battlecry": NatalieSeline,
			"Classic~Rogue~Spell~0~Preparation": Preparation,
			"Classic~Rogue~Spell~0~Shadowstep": Shadowstep,
			"Classic~Rogue~Spell~1~Pilfer": Pilfer,
			"Classic~Rogue~Spell~2~Betrayal": Betrayal,
			"Classic~Rogue~Spell~2~Cold Blood~Combo": ColdBlood,
			"Classic~Rogue~Minion~2~2~2~None~Defias Ringleader~Combo": DefiasRingleader,
			"Classic~Rogue~Minion~1~2~1~None~Defias Bandit~Uncollectible": DefiasBandit,
			"Classic~Rogue~Spell~2~Eviscerate~Combo": Eviscerate,
			"Classic~Rogue~Minion~2~1~1~None~Patient Assassin~Poisonous~Stealth": PatientAssassin,
			"Classic~Rogue~Minion~3~2~2~None~Edwin VanCleef~Combo~Legendary": EdwinVanCleef,
			"Classic~Rogue~Spell~3~Headcrack~Combo": Headcrack,
			"Classic~Rogue~Weapon~3~2~2~Perdition's Blade~Combo~Battlecry": PerditionsBlade,
			"Classic~Rogue~Minion~3~3~3~None~SI:7 Agent~Combo": SI7Agent,
			"Classic~Rogue~Spell~4~Blade Flurry": BladeFlurry,
			"Classic~Rogue~Minion~4~4~4~None~Master of Disguise~Battlecry": MasterofDisguise,
			"Classic~Rogue~Minion~6~5~3~None~Kidnapper~Combo": Kidnapper,
			"Classic~Shaman~Minion~1~3~1~Elemental~Dust Devil~Overload~Windfury": DustDevil,
			"Classic~Shaman~Spell~1~Earth Shock": EarthShock,
			"Classic~Shaman~Spell~1~Forked Lightning~Overload": ForkedLightning,
			"Classic~Shaman~Spell~1~Lightning Bolt~Overload": LightningBolt,
			"Classic~Shaman~Spell~2~Ancestral Spirit": AncestralSpirit,
			"Classic~Shaman~Weapon~2~2~3~Stormforged Axe~Overload": StormforgedAxe,
			"Classic~Shaman~Spell~3~Far Sight": FarSight,
			"Classic~Shaman~Spell~3~Feral Spirit~Overload": FeralSpirit,
			"Classic~Shaman~Minion~2~2~3~None~Spirit Wolf~Taunt~Uncollectible": SpiritWolf,
			"Classic~Shaman~Spell~3~Lava Burst~Overload": LavaBurst,
			"Classic~Shaman~Spell~3~Lightning Storm~Overload": LightningStorm,
			"Classic~Shaman~Minion~3~0~3~Totem~Mana Tide Totem": ManaTideTotem,
			"Classic~Shaman~Minion~3~2~4~Elemental~Unbound Elemental": UnboundElemental,
			"Classic~Shaman~Weapon~5~2~8~Doomhammer~Windfury~Overload": Doomhammer,
			"Classic~Shaman~Minion~5~7~8~Elemental~Earth Elemental~Taunt~Overload": EarthElemental,
			"Classic~Shaman~Minion~8~3~5~Elemental~Al'Akir the Windlord~Taunt~Charge~Windfury~Divine Shield~Legendary": AlAkirtheWindlord,
			"Classic~Warlock~Minion~1~0~1~Demon~Blood Imp~Stealth": BloodImp,
			"Classic~Warlock~Spell~1~Call of the Void": CalloftheVoid,
			"Classic~Warlock~Minion~1~3~2~Demon~Flame Imp~Battlecry": FlameImp,
			"Classic~Warlock~Spell~2~Demonfire": Demonfire,
			"Classic~Warlock~Spell~3~Sense Demons": SenseDemons,
			"Classic~Warlock~Minion~4~0~4~None~Summoning Portal": SummoningPortal,
			"Classic~Warlock~Minion~3~3~5~Demon~Felguard~Taunt~Battlecry": Felguard,
			"Classic~Warlock~Minion~3~3~3~Demon~Void Terror~Battlecry": VoidTerror,
			"Classic~Warlock~Minion~4~5~6~Demon~Pit Lord~Battlecry": PitLord,
			"Classic~Warlock~Spell~4~Shadowflame": Shadowflame,
			"Classic~Warlock~Spell~5~Bane of Doom": BaneofDoom,
			"Classic~Warlock~Spell~6~Siphon Soul": SiphonSoul,
			"Classic~Warlock~Minion~7~5~8~Demon~Siegebreaker~Taunt": Siegebreaker,
			"Classic~Warlock~Spell~8~Twisting Nether": TwistingNether,
			"Classic~Warlock~Minion~9~3~15~Demon~Lord Jaraxxus~Battlecry~Legendary": LordJaraxxus,
			"Classic~Warlock~Minion~6~6~6~Demon~Infernal~Uncollectible": Infernal,
			"Classic~Warlock~Weapon~3~3~8~Blood Fury~Uncollectible": BloodFury,
			"Classic~Warrior~Spell~0~Inner Rage": InnerRage,
			"Classic~Warrior~Spell~1~Shield Slam": ShieldSlam,
			"Classic~Warrior~Spell~1~Upgrade!": Upgrade,
			"Classic~Warrior~Weapon~1~1~3~Heavy Axe~Uncollectible": HeavyAxe,
			"Classic~Warrior~Minion~2~1~4~None~Armorsmith": Armorsmith,
			"Classic~Warrior~Spell~2~Battle Rage": BattleRage,
			"Classic~Warrior~Spell~2~Commanding Shout": CommandingShout,
			"Classic~Warrior~Minion~2~2~2~None~Cruel Taskmaster~Battlecry": CruelTaskmaster,
			"Classic~Warrior~Spell~2~Rampage": Rampage,
			"Classic~Warrior~Spell~2~Slam": Slam,
			"Classic~Warrior~Minion~3~2~4~None~Frothing Berserker": FrothingBerserker,
			"Classic~Warrior~Minion~4~3~3~None~Arathi Weaponsmith~Battlecry": ArathiWeaponsmith,
			"Classic~Warrior~Weapon~1~2~2~Battle Axe~Uncollectible": BattleAxe,
			"Classic~Warrior~Spell~4~Mortal Strike": MortalStrike,
			"Classic~Warrior~Spell~5~Brawl": Brawl,
			"Classic~Warrior~Weapon~7~7~1~Gorehowl": Gorehowl,
			"Classic~Warrior~Minion~8~4~9~None~Grommash Hellscream~Charge~Legendary": GrommashHellscream,
		}

MinionswithRace = {
			'Beast': {
				"Basic~Neutral~Minion~1~1~1~Beast~Stonetusk Boar~Charge": StonetuskBoar,
				"Basic~Neutral~Minion~2~3~2~Beast~Bloodfen Raptor": BloodfenRaptor,
				"Basic~Neutral~Minion~2~2~3~Beast~River Crocolisk": RiverCrocolisk,
				"Basic~Neutral~Minion~3~3~3~Beast~Ironfur Grizzly~Taunt": IronfurGrizzly,
				"Basic~Neutral~Minion~3~1~4~Beast~Silverback Patriarch~Taunt": SilverbackPatriarch,
				"Basic~Neutral~Minion~4~2~7~Beast~Oasis Snapjaw": OasisSnapjaw,
				"Basic~Neutral~Minion~7~9~5~Beast~Core Hound": CoreHound,
				"Basic~Hunter~Minion~1~1~1~Beast~Timber Wolf": TimberWolf,
				"Basic~Hunter~Minion~5~3~2~Beast~Starving Buzzard": StarvingBuzzard,
				"Basic~Hunter~Minion~5~2~5~Beast~Tundra Rhino": TundraRhino,
				"Classic~Neutral~Minion~1~1~1~Beast~Angry Chicken": AngryChicken,
				"Classic~Neutral~Minion~1~1~2~Beast~Hungry Crab~Battlecry": HungryCrab,
				"Classic~Neutral~Minion~1~1~1~Beast~Young Dragonhawk~Windfury": YoungDragonhawk,
				"Classic~Neutral~Minion~2~2~2~Beast~Dire Wolf Alpha": DireWolfAlpha,
				"Classic~Neutral~Minion~3~2~3~Beast~Emperor Cobra~Poisonous": EmperorCobra,
				"Classic~Neutral~Minion~3~2~1~Beast~Ironbeak Owl~Battlecry": IronbeakOwl,
				"Classic~Neutral~Minion~3~4~2~Beast~Jungle Panther~Stealth": JunglePanther,
				"Classic~Neutral~Minion~3~5~5~Beast~King Mukla~Battlecry~Legendary": KingMukla,
				"Classic~Neutral~Minion~5~3~5~Beast~Stampeding Kodo~Battlecry": StampedingKodo,
				"Classic~Neutral~Minion~5~5~5~Beast~Stranglethorn Tiger~Stealth": StranglethornTiger,
				"Classic~Neutral~Minion~6~9~7~Beast~The Beast~Deathrattle~Legendary": TheBeast,
				"Classic~Hunter~Minion~2~2~2~Beast~Scavenging Hyena": ScavengingHyena,
				"Classic~Hunter~Minion~6~6~5~Beast~Savannah Highmane~Deathrattle": SavannahHighmane,
				"Classic~Hunter~Minion~9~8~8~Beast~King Krush~Charge~Legendary": KingKrush,
				"Classic~Monk~Minion~1~1~1~Beast~Xuen, the White Tiger~Rush~Legendary": XuentheWhiteTiger_Mutable_1,
				"Classic~Monk~Minion~5~3~5~Beast~Spawn of Xuen~Rush~Battlecry": SpawnofXuen,
			},
			'Demon': {
				"Basic~Demon Hunter~Minion~1~2~1~Demon~Shadowhoof Slayer~Battlecry": ShadowhoofSlayer,
				"Basic~Demon Hunter~Minion~2~3~2~Demon~Sightless Watcher~Battlecry": SightlessWatcher,
				"Basic~Demon Hunter~Minion~3~4~2~Demon~Satyr Overseer": SatyrOverseer,
				"Basic~Warlock~Minion~1~1~3~Demon~Voidwalker~Taunt": Voidwalker,
				"Basic~Warlock~Minion~2~4~3~Demon~Felstalker~Battlecry": Felstalker,
				"Basic~Warlock~Minion~6~6~6~Demon~Dread Infernal~Battlecry": DreadInfernal,
				"Classic~Neutral~Minion~6~7~5~Demon~Illidan Stormrage~Legendary": Xavius,
				"Classic~Warlock~Minion~1~0~1~Demon~Blood Imp~Stealth": BloodImp,
				"Classic~Warlock~Minion~1~3~2~Demon~Flame Imp~Battlecry": FlameImp,
				"Classic~Warlock~Minion~3~3~5~Demon~Felguard~Taunt~Battlecry": Felguard,
				"Classic~Warlock~Minion~3~3~3~Demon~Void Terror~Battlecry": VoidTerror,
				"Classic~Warlock~Minion~4~5~6~Demon~Pit Lord~Battlecry": PitLord,
				"Classic~Warlock~Minion~7~5~8~Demon~Siegebreaker~Taunt": Siegebreaker,
				"Classic~Warlock~Minion~9~3~15~Demon~Lord Jaraxxus~Battlecry~Legendary": LordJaraxxus,
			},
			'Dragon': {
				"Classic~Neutral~Minion~2~3~2~Dragon~Faerie Dragon": FaerieDragon,
				"Classic~Neutral~Minion~3~3~2~Dragon~Brightwing~Battlecry~Legendary": Brightwing,
				"Classic~Neutral~Minion~4~4~1~Dragon~Twilight Drake~Battlecry": TwilightDrake,
				"Classic~Neutral~Minion~9~8~8~Dragon~Alexstrasza~Battlecry~Legendary": Alexstrasza,
				"Classic~Neutral~Minion~9~4~12~Dragon~Malygos~Spell Damage~Legendary": Malygos,
				"Classic~Neutral~Minion~9~8~8~Dragon~Nozdormu~Legendary": Nozdormu,
				"Classic~Neutral~Minion~9~8~8~Dragon~Onyxia~Battlecry~Legendary": Onyxia,
				"Classic~Neutral~Minion~9~4~12~Dragon~Ysera~Legendary": Ysera,
				"Classic~Neutral~Minion~10~12~12~Dragon~Deathwing~Battlecry~Legendary": Deathwing,
			},
			'Elemental': {
				"Basic~Neutral~Minion~3~5~1~Elemental~Magma Rager": MagmaRager,
				"Basic~Mage~Minion~4~3~6~Elemental~Water Elemental": WaterElemental,
				"Basic~Shaman~Minion~6~6~5~Elemental~Fire Elemental~Battlecry": FireElemental,
				"Classic~Neutral~Minion~6~5~5~Elemental~Frost Elemental~Battlecry": FrostElemental,
				"Classic~Neutral~Minion~7~7~5~Elemental~Baron Geddon~Legendary": BaronGeddon,
				"Classic~Neutral~Minion~8~5~5~Elemental~Arcane Devourer": ArcaneDevourer,
				"Classic~Shaman~Minion~1~3~1~Elemental~Dust Devil~Overload~Windfury": DustDevil,
				"Classic~Shaman~Minion~3~2~4~Elemental~Unbound Elemental": UnboundElemental,
				"Classic~Shaman~Minion~5~7~8~Elemental~Earth Elemental~Taunt~Overload": EarthElemental,
				"Classic~Shaman~Minion~8~3~5~Elemental~Al'Akir the Windlord~Taunt~Charge~Windfury~Divine Shield~Legendary": AlAkirtheWindlord,
			},
			'Murloc': {
				"Basic~Neutral~Minion~1~1~1~Murloc~Grimscale Oracle": GrimscaleOracle,
				"Basic~Neutral~Minion~1~2~1~Murloc~Murloc Raider": MurlocRaider,
				"Basic~Neutral~Minion~2~2~1~Murloc~Bluegill Warrior~Charge": BluegillWarrior,
				"Basic~Neutral~Minion~2~2~1~Murloc~Murloc Tidehunter~Battlecry": MurlocTidehunter,
				"Classic~Neutral~Minion~1~1~2~Murloc~Murloc Tidecaller": MurlocTidecaller,
				"Classic~Neutral~Minion~3~2~3~Murloc~Coldlight Seer~Battlecry": ColdlightSeer,
				"Classic~Neutral~Minion~3~3~3~Murloc~Murloc Warleader": MurlocWarleader,
			},
			'Mech': {
				"Classic~Neutral~Minion~3~0~3~Mech~Alarm-o-Bot": AlarmoBot,
				"Classic~Neutral~Minion~3~1~4~Mech~Demolisher": Demolisher,
				"Classic~Neutral~Minion~3~2~3~Mech~Harvest Golem~Deathrattle": HarvestGolem,
			},
			'Pirate': {
				"Classic~Neutral~Minion~1~1~2~Pirate~Bloodsail Corsair~Battlecry": BloodsailCorsair,
				"Classic~Neutral~Minion~1~2~1~Pirate~Southsea Deckhand": SouthseaDeckhand,
				"Classic~Neutral~Minion~2~2~3~Pirate~Bloodsail Raider~Battlecry": BloodsailRaider,
				"Classic~Neutral~Minion~3~3~3~Pirate~Southsea Captain": SouthseaCaptain,
				"Classic~Neutral~Minion~4~3~3~Pirate~Dread Corsair~Taunt": DreadCorsair,
				"Classic~Neutral~Minion~5~5~4~Pirate~Captain Greenskin~Battlecry~Legendary": CaptainGreenskin,
			},
			'Totem': {
				"Basic~Shaman~Minion~3~0~3~Totem~Flametongue Totem": FlametongueTotem,
				"Classic~Shaman~Minion~3~0~3~Totem~Mana Tide Totem": ManaTideTotem,
			},
			}

MinionsofCost = {
			1: {
			"Basic~Neutral~Minion~1~1~1~None~Elven Archer~Battlecry": ElvenArcher,
			"Basic~Neutral~Minion~1~1~2~None~Goldshire Footman~Taunt": GoldshireFootman,
			"Basic~Neutral~Minion~1~1~1~Murloc~Grimscale Oracle": GrimscaleOracle,
			"Basic~Neutral~Minion~1~2~1~Murloc~Murloc Raider": MurlocRaider,
			"Basic~Neutral~Minion~1~1~1~Beast~Stonetusk Boar~Charge": StonetuskBoar,
			"Basic~Neutral~Minion~1~2~1~None~Voodoo Doctor~Battlecry": VoodooDoctor,
			"Basic~Demon Hunter~Minion~1~2~1~Demon~Shadowhoof Slayer~Battlecry": ShadowhoofSlayer,
			"Basic~Hunter~Minion~1~1~1~Beast~Timber Wolf": TimberWolf,
			"Basic~Monk~Minion~1~0~2~None~Arch of the Temple~Taunt~Battlecry": ArchoftheTemple,
			"Basic~Monk~Minion~1~1~3~None~Monk's Apprentice": MonksApprentice,
			"Basic~Priest~Minion~1~1~1~None~Psychic Conjurer-Battlecry": PsychicConjurer,
			"Basic~Warlock~Minion~1~1~3~Demon~Voidwalker~Taunt": Voidwalker,
			"Classic~Neutral~Minion~1~1~1~None~Abusive Sergeant~Battlecry": AbusiveSergeant,
			"Classic~Neutral~Minion~1~1~1~None~Argent Squire~Divine Shield": ArgentSquire,
			"Classic~Neutral~Minion~1~1~1~Beast~Angry Chicken": AngryChicken,
			"Classic~Neutral~Minion~1~1~2~Pirate~Bloodsail Corsair~Battlecry": BloodsailCorsair,
			"Classic~Neutral~Minion~1~1~2~Beast~Hungry Crab~Battlecry": HungryCrab,
			"Classic~Neutral~Minion~1~1~1~None~Leper Gnome~Deathrattle": LeperGnome,
			"Classic~Neutral~Minion~1~1~2~None~Lightwarden": Lightwarden,
			"Classic~Neutral~Minion~1~1~2~Murloc~Murloc Tidecaller": MurlocTidecaller,
			"Classic~Neutral~Minion~1~1~2~None~Secretkeeper": Secretkeeper,
			"Classic~Neutral~Minion~1~0~4~None~Shieldbearer~Taunt": Shieldbearer,
			"Classic~Neutral~Minion~1~2~1~Pirate~Southsea Deckhand": SouthseaDeckhand,
			"Classic~Neutral~Minion~1~2~1~None~Worgen Infiltrator~Stealth": WorgenInfiltrator,
			"Classic~Neutral~Minion~1~1~1~Beast~Young Dragonhawk~Windfury": YoungDragonhawk,
			"Classic~Neutral~Minion~1~2~1~None~Young Priestess": YoungPriestess,
			"Classic~Monk~Minion~1~0~4~None~Wise Lorewalker Cho~Battlecry~Legendary": WiseLorewalkerCho,
			"Classic~Monk~Minion~1~1~1~Beast~Xuen, the White Tiger~Rush~Legendary": XuentheWhiteTiger_Mutable_1,
			"Classic~Priest~Minion~1~2~1~None~Scarlet Subjugator~Battlecry": ScarletSubjugator,
			"Classic~Shaman~Minion~1~3~1~Elemental~Dust Devil~Overload~Windfury": DustDevil,
			"Classic~Warlock~Minion~1~0~1~Demon~Blood Imp~Stealth": BloodImp,
			"Classic~Warlock~Minion~1~3~2~Demon~Flame Imp~Battlecry": FlameImp,
			},
			2: {
			"Basic~Neutral~Minion~2~3~2~None~Acidic Swamp Ooze~Battlecry": AcidicSwampOoze,
			"Basic~Neutral~Minion~2~3~2~Beast~Bloodfen Raptor": BloodfenRaptor,
			"Basic~Neutral~Minion~2~2~1~Murloc~Bluegill Warrior~Charge": BluegillWarrior,
			"Basic~Neutral~Minion~2~2~2~None~Frostwolf Grunt~Taunt": FrostwolfGrunt,
			"Basic~Neutral~Minion~2~2~2~None~Kobold Geomancer~Spell Damage": KoboldGeomancer,
			"Basic~Neutral~Minion~2~2~1~Murloc~Murloc Tidehunter~Battlecry": MurlocTidehunter,
			"Basic~Neutral~Minion~2~1~1~None~Novice Engineer~Battlecry": NoviceEngineer,
			"Basic~Neutral~Minion~2~2~3~Beast~River Crocolisk": RiverCrocolisk,
			"Basic~Demon Hunter~Minion~2~3~2~Demon~Sightless Watcher~Battlecry": SightlessWatcher,
			"Basic~Monk~Minion~2~1~4~None~Swift Brewmaster": SwiftBrewmaster,
			"Basic~Warlock~Minion~2~4~3~Demon~Felstalker~Battlecry": Felstalker,
			"Classic~Neutral~Minion~2~2~3~None~Amani Berserker": AmaniBerserker,
			"Classic~Neutral~Minion~2~4~5~None~Ancient Watcher": AncientWatcher,
			"Classic~Neutral~Minion~2~1~1~None~Bloodmage Thalnos~Deathrattle~Spell Damage~Legendary": BloodmageThalnos,
			"Classic~Neutral~Minion~2~2~3~Pirate~Bloodsail Raider~Battlecry": BloodsailRaider,
			"Classic~Neutral~Minion~2~2~2~None~Crazed Alchemist~Battlecry": CrazedAlchemist,
			"Classic~Neutral~Minion~2~2~2~Beast~Dire Wolf Alpha": DireWolfAlpha,
			"Classic~Neutral~Minion~2~0~7~None~Doomsayer": Doomsayer,
			"Classic~Neutral~Minion~2~3~2~Dragon~Faerie Dragon": FaerieDragon,
			"Classic~Neutral~Minion~2~2~2~None~Knife Juggler": KnifeJuggler,
			"Classic~Neutral~Minion~2~2~1~None~Loot Hoarder~Deathrattle": LootHoarder,
			"Classic~Neutral~Minion~2~0~4~None~Lorewalker Cho~Legendary": LorewalkerCho,
			"Classic~Neutral~Minion~2~3~2~None~Mad Bomber~Battlecry": MadBomber,
			"Classic~Neutral~Minion~2~1~3~None~Mana Addict": ManaAddict,
			"Classic~Neutral~Minion~2~2~2~None~Mana Wraith": ManaWraith,
			"Classic~Neutral~Minion~2~1~3~None~Master Swordsmith": MasterSwordsmith,
			"Classic~Neutral~Minion~2~4~4~None~Millhouse Manastorm~Battlecry~Legendary": MillhouseManastorm,
			"Classic~Neutral~Minion~2~0~4~None~Nat Pagle~Legendary": NatPagle,
			"Classic~Neutral~Minion~2~2~2~None~Pint-Sized Summoner": PintSizedSummoner,
			"Classic~Neutral~Minion~2~2~3~None~Sunfury Protector~Battlecry": SunfuryProtector,
			"Classic~Neutral~Minion~2~3~2~None~Wild Pyromancer": WildPyromancer,
			"Classic~Neutral~Minion~2~3~2~None~Youthful Brewmaster~Battlecry": YouthfulBrewmaster,
			"Classic~Hunter~Minion~2~2~2~Beast~Scavenging Hyena": ScavengingHyena,
			"Classic~Mage~Minion~2~1~3~None~Mana Wyrm": ManaWyrm,
			"Classic~Mage~Minion~2~3~2~None~Sorcerer's Apprentice": SorcerersApprentice,
			"Classic~Monk~Minion~2~2~3~None~Defense Technique Master~Taunt~Quaff": DefenseTechniqueMaster,
			"Classic~Paladin~Minion~2~2~2~None~Argent Protector~Battlecry": ArgentProtector,
			"Classic~Priest~Minion~2~2~3~None~Kul Tiran Chaplain~Battlecry": KulTiranChaplain,
			"Classic~Priest~Minion~2~0~5~None~Lightwell": Lightwell,
			"Classic~Rogue~Minion~2~2~2~None~Defias Ringleader~Combo": DefiasRingleader,
			"Classic~Rogue~Minion~2~1~1~None~Patient Assassin~Poisonous~Stealth": PatientAssassin,
			"Classic~Warrior~Minion~2~1~4~None~Armorsmith": Armorsmith,
			"Classic~Warrior~Minion~2~2~2~None~Cruel Taskmaster~Battlecry": CruelTaskmaster,
			},
			3: {
			"Basic~Neutral~Minion~3~1~4~None~Dalaran Mage~Spell Damage": DalaranMage,
			"Basic~Neutral~Minion~3~2~2~None~Ironforge Rifleman~Battlecry": IronforgeRifleman,
			"Basic~Neutral~Minion~3~3~3~Beast~Ironfur Grizzly~Taunt": IronfurGrizzly,
			"Basic~Neutral~Minion~3~5~1~Elemental~Magma Rager": MagmaRager,
			"Basic~Neutral~Minion~3~2~2~None~Raid Leader": RaidLeader,
			"Basic~Neutral~Minion~3~2~3~None~Razorfen Hunter~Battlecry": RazorfenHunter,
			"Basic~Neutral~Minion~3~3~2~None~Shattered Sun Cleric~Battlecry": ShatteredSunCleric,
			"Basic~Neutral~Minion~3~1~4~Beast~Silverback Patriarch~Taunt": SilverbackPatriarch,
			"Basic~Neutral~Minion~3~3~1~None~Wolfrider~Charge": Wolfrider,
			"Basic~Demon Hunter~Minion~3~4~2~Demon~Satyr Overseer": SatyrOverseer,
			"Basic~Monk~Minion~3~1~4~None~Sweeping Kick Fighter~Rush": SweepingKickFighter,
			"Basic~Monk~Minion~3~3~4~None~Shado-Pan Wu Kao": ShadoPanWuKao,
			"Basic~Shaman~Minion~3~0~3~Totem~Flametongue Totem": FlametongueTotem,
			"Basic~Warrior~Minion~3~2~3~None~Warsong Commander": WarsongCommander,
			"Classic~Neutral~Minion~3~0~3~Mech~Alarm-o-Bot": AlarmoBot,
			"Classic~Neutral~Minion~3~4~4~None~Arcane Golem~Battlecry": ArcaneGolem,
			"Classic~Neutral~Minion~3~3~3~None~Blood Knight~Battlecry": BloodKnight,
			"Classic~Neutral~Minion~3~3~2~Dragon~Brightwing~Battlecry~Legendary": Brightwing,
			"Classic~Neutral~Minion~3~2~3~Murloc~Coldlight Seer~Battlecry": ColdlightSeer,
			"Classic~Neutral~Minion~3~1~4~Mech~Demolisher": Demolisher,
			"Classic~Neutral~Minion~3~3~3~None~Earthen Ring Farseer~Battlecry": EarthenRingFarseer,
			"Classic~Neutral~Minion~3~2~3~Beast~Emperor Cobra~Poisonous": EmperorCobra,
			"Classic~Neutral~Minion~3~2~3~None~Flesheating Ghoul": FlesheatingGhoul,
			"Classic~Neutral~Minion~3~2~3~Mech~Harvest Golem~Deathrattle": HarvestGolem,
			"Classic~Neutral~Minion~3~1~5~None~Imp Master": ImpMaster,
			"Classic~Neutral~Minion~3~4~7~None~Injured Blademaster~Battlecry": InjuredBlademaster,
			"Classic~Neutral~Minion~3~2~1~Beast~Ironbeak Owl~Battlecry": IronbeakOwl,
			"Classic~Neutral~Minion~3~4~2~Beast~Jungle Panther~Stealth": JunglePanther,
			"Classic~Neutral~Minion~3~5~5~Beast~King Mukla~Battlecry~Legendary": KingMukla,
			"Classic~Neutral~Minion~3~3~3~Murloc~Murloc Warleader": MurlocWarleader,
			"Classic~Neutral~Minion~3~2~2~None~Questing Adventurer": QuestingAdventurer,
			"Classic~Neutral~Minion~3~3~3~None~Raging Worgen": RagingWorgen,
			"Classic~Neutral~Minion~3~3~1~None~Scarlet Crusader~Divine Shield": ScarletCrusader,
			"Classic~Neutral~Minion~3~3~3~Pirate~Southsea Captain": SouthseaCaptain,
			"Classic~Neutral~Minion~3~2~3~None~Tauren Warrior~Taunt": TaurenWarrior,
			"Classic~Neutral~Minion~3~2~3~None~Thrallmar Farseer~Windfury": ThrallmarFarseer,
			"Classic~Neutral~Minion~3~3~3~None~Tinkmaster Overspark~Battlecry~Legendary": TinkmasterOverspark,
			"Classic~Mage~Minion~3~4~3~None~Kirin Tor Mage~Battlecry": KirinTorMage,
			"Classic~Paladin~Minion~3~3~3~None~Ardor Peacekeeper~Battlecry": AldorPeacekeeper,
			"Classic~Rogue~Minion~3~2~2~None~Edwin VanCleef~Combo~Legendary": EdwinVanCleef,
			"Classic~Rogue~Minion~3~3~3~None~SI:7 Agent~Combo": SI7Agent,
			"Classic~Shaman~Minion~3~0~3~Totem~Mana Tide Totem": ManaTideTotem,
			"Classic~Shaman~Minion~3~2~4~Elemental~Unbound Elemental": UnboundElemental,
			"Classic~Warlock~Minion~3~3~5~Demon~Felguard~Taunt~Battlecry": Felguard,
			"Classic~Warlock~Minion~3~3~3~Demon~Void Terror~Battlecry": VoidTerror,
			"Classic~Warrior~Minion~3~2~4~None~Frothing Berserker": FrothingBerserker,
			},
			4: {
			"Basic~Neutral~Minion~4~4~5~None~Chillwind Yeti": ChillwindYeti,
			"Basic~Neutral~Minion~4~2~4~None~Dragonling Mechanic~Battlecry": DragonlingMechanic,
			"Basic~Neutral~Minion~4~2~4~None~Gnomish Inventor~Battlecry": GnomishInventor,
			"Basic~Neutral~Minion~4~2~7~Beast~Oasis Snapjaw": OasisSnapjaw,
			"Basic~Neutral~Minion~4~4~4~None~Ogre Magi~Spell Damage": OgreMagi,
			"Basic~Neutral~Minion~4~3~5~None~Sen'jin Shieldmasta~Taunt": SenjinShieldmasta,
			"Basic~Neutral~Minion~4~2~5~None~Stormwind Knight~Charge": StormwindKnight,
			"Basic~Hunter~Minion~4~4~3~None~Houndmaster~Battlecry": Houndmaster,
			"Basic~Mage~Minion~4~3~6~Elemental~Water Elemental": WaterElemental,
			"Basic~Rogue~Minion~4~3~3~None~Plaguebringer~Battlecry": Plaguebringer,
			"Basic~Shaman~Minion~4~3~3~None~Windspeaker~Battlecry": Windspeaker,
			"Basic~Warrior~Minion~4~4~3~None~Kor'kron Elite~Charge": KorkronElite,
			"Classic~Neutral~Minion~4~5~4~None~Ancient Brewmaster~Battlecry": AncientBrewmaster,
			"Classic~Neutral~Minion~4~2~5~None~Ancient Mage~Battlecry": AncientMage,
			"Classic~Neutral~Minion~4~4~2~None~Cult Master": CultMaster,
			"Classic~Neutral~Minion~4~4~4~None~Dark Iron Dwarf~Battlecry": DarkIronDwarf,
			"Classic~Neutral~Minion~4~2~3~None~Defender of Argus~Battlecry": DefenderofArgus,
			"Classic~Neutral~Minion~4~3~3~Pirate~Dread Corsair~Taunt": DreadCorsair,
			"Classic~Neutral~Minion~4~1~7~None~Mogu'shan Warden~Taunt": MogushanWarden,
			"Classic~Neutral~Minion~4~3~3~None~Silvermoon Guardian~Divine Shield": SilvermoonGuardian,
			"Classic~Neutral~Minion~4~5~4~None~SI:7 Infiltrator~Battlecry": SI7Infiltrator,
			"Classic~Neutral~Minion~4~4~1~Dragon~Twilight Drake~Battlecry": TwilightDrake,
			"Classic~Neutral~Minion~4~3~5~None~Violet Teacher": VioletTeacher,
			"Classic~Druid~Minion~4~2~2~None~Keeper of the Grove~Choose One": KeeperoftheGrove,
			"Classic~Mage~Minion~4~3~3~None~Ethereal Arcanist": EtherealArcanist,
			"Classic~Monk~Minion~4~5~4~Monk~Onima Actuary~Stealth": OnimaActuary,
			"Classic~Monk~Minion~4~5~3~None~Pawn of Shaohao~Rush~Windfury": PawnofShaohao,
			"Classic~Monk~Minion~4~3~5~None~Shaohao, the Emperor~Battlecry~Legendary": ShaohaotheEmperor,
			"Classic~Priest~Minion~4~0~5~None~Lightspawn": Lightspawn,
			"Classic~Rogue~Minion~4~4~4~None~Master of Disguise~Battlecry": MasterofDisguise,
			"Classic~Warlock~Minion~4~0~4~None~Summoning Portal": SummoningPortal,
			"Classic~Warlock~Minion~4~5~6~Demon~Pit Lord~Battlecry": PitLord,
			"Classic~Warrior~Minion~4~3~3~None~Arathi Weaponsmith~Battlecry": ArathiWeaponsmith,
			},
			5: {
			"Basic~Neutral~Minion~5~5~4~None~Booty Bay Bodyguard~Taunt": BootyBayBodyguard,
			"Basic~Neutral~Minion~5~4~5~None~Darkscale Healer~Battlecry": DarkscaleHealer,
			"Basic~Neutral~Minion~5~4~4~None~Frostwolf Warlord~Battlecry": FrostwolfWarlord,
			"Basic~Neutral~Minion~5~2~7~None~Gurubashi Berserker": GurubashiBerserker,
			"Basic~Neutral~Minion~5~4~4~None~Nightblade~Battlecry": Nightblade,
			"Basic~Neutral~Minion~5~4~2~None~Stormpike Commando~Battlecry": StormpikeCommando,
			"Basic~Demon Hunter~Minion~5~7~4~None~Glaivebound Adept~Battlecry": GlaiveboundAdept,
			"Basic~Hunter~Minion~5~3~2~Beast~Starving Buzzard": StarvingBuzzard,
			"Basic~Hunter~Minion~5~2~5~Beast~Tundra Rhino": TundraRhino,
			"Classic~Neutral~Minion~5~4~4~None~Abomination~Taunt~Deathrattle": Abomination,
			"Classic~Neutral~Minion~5~4~2~None~Big Game Hunter~Battlecry": BigGameHunter,
			"Classic~Neutral~Minion~5~5~4~Pirate~Captain Greenskin~Battlecry~Legendary": CaptainGreenskin,
			"Classic~Neutral~Minion~5~3~3~None~Faceless Manipulator~Battlecry": FacelessManipulator,
			"Classic~Neutral~Minion~5~3~6~None~Fen Creeper~Taunt": FenCreeper,
			"Classic~Neutral~Minion~5~5~4~None~Harrison Jones~Battlecry~Legendary": HarrisonJones,
			"Classic~Neutral~Minion~5~4~4~None~Silver Hand Knight~Battlecry": SilverHandKnight,
			"Classic~Neutral~Minion~5~4~6~None~Spiteful Smith": SpitefulSmith,
			"Classic~Neutral~Minion~5~3~5~Beast~Stampeding Kodo~Battlecry": StampedingKodo,
			"Classic~Neutral~Minion~5~5~5~Beast~Stranglethorn Tiger~Stealth": StranglethornTiger,
			"Classic~Neutral~Minion~5~7~6~None~Venture Co. Mercenary": VentureCoMercenary,
			"Classic~Druid~Minion~5~4~4~None~Druid of the Claw~Choose One": DruidoftheClaw,
			"Classic~Monk~Minion~5~3~5~Beast~Spawn of Xuen~Rush~Battlecry": SpawnofXuen,
			"Classic~Priest~Minion~5~5~6~None~Temple Enforcer~Battlecry": TempleEnforcer,
			"Classic~Shaman~Minion~5~7~8~Elemental~Earth Elemental~Taunt~Overload": EarthElemental,
			},
			6: {
			"Basic~Neutral~Minion~6~6~5~None~Lord of the Arena~Taunt": LordoftheArena,
			"Basic~Neutral~Minion~6~4~7~None~Archmage~Spell Damage": Archmage,
			"Basic~Neutral~Minion~6~6~7~None~Boulderfist Ogre": BoulderfistOgre,
			"Basic~Neutral~Minion~6~5~2~None~Reckless Rocketeer~Charge": RecklessRocketeer,
			"Basic~Shaman~Minion~6~6~5~Elemental~Fire Elemental~Battlecry": FireElemental,
			"Basic~Warlock~Minion~6~6~6~Demon~Dread Infernal~Battlecry": DreadInfernal,
			"Classic~Neutral~Minion~6~4~2~None~Argent Commander~Divine Shield~Charge": ArgentCommander,
			"Classic~Neutral~Minion~6~4~5~None~Cairne Bloodhoof~Deathrattle~Legendary": CairneBloodhoof,
			"Classic~Neutral~Minion~6~5~5~Elemental~Frost Elemental~Battlecry": FrostElemental,
			"Classic~Neutral~Minion~6~4~4~None~Gadgetzan Auctioneer": GadgetzanAuctioneer,
			"Classic~Neutral~Minion~6~4~4~None~Hogger~Legendary": Hogger,
			"Classic~Neutral~Minion~6~7~5~Demon~Illidan Stormrage~Legendary": Xavius,
			"Classic~Neutral~Minion~6~5~4~None~Priestess of Elune~Battlecry": PriestessofElune,
			"Classic~Neutral~Minion~6~4~5~None~Sunwalker~Divine Shield~Taunt": Sunwalker,
			"Classic~Neutral~Minion~6~9~7~Beast~The Beast~Deathrattle~Legendary": TheBeast,
			"Classic~Neutral~Minion~6~4~5~None~The Black Knight~Battlecry~Legendary": TheBlackKnight,
			"Classic~Neutral~Minion~6~4~5~None~Windfury Harpy~Windfury": WindfuryHarpy,
			"Classic~Hunter~Minion~6~6~5~Beast~Savannah Highmane~Deathrattle": SavannahHighmane,
			"Classic~Monk~Minion~6~3~7~None~Lotus Healer~Taunt": LotusHealer,
			"Classic~Priest~Minion~6~4~5~None~Cabal Shadow Priest~Battlecry": CabalShadowPriest,
			"Classic~Rogue~Minion~6~5~3~None~Kidnapper~Combo": Kidnapper,
			},
			7: {
			"Basic~Neutral~Minion~7~9~5~Beast~Core Hound": CoreHound,
			"Basic~Neutral~Minion~7~6~6~None~Stormwind Champion": StormwindChampion,
			"Basic~Neutral~Minion~7~7~7~None~War Golem": WarGolem,
			"Basic~Paladin~Minion~7~5~6~None~Guardian of Kings~Battlecry": GuardianofKings,
			"Classic~Neutral~Minion~7~4~4~None~Barrens Stablehand~Battlecry": BarrensStablehand,
			"Classic~Neutral~Minion~7~7~5~Elemental~Baron Geddon~Legendary": BaronGeddon,
			"Classic~Neutral~Minion~7~6~8~None~High Inquisitor Whitemane~Battlecry~Legendary": HighInquisitorWhitemane,
			"Classic~Neutral~Minion~7~7~5~None~Ravenholdt Assassin~Stealth": RavenholdtAssassin,
			"Classic~Druid~Minion~7~5~5~None~Ancient of Lore~Choose One": AncientofLore,
			"Classic~Druid~Minion~7~5~5~None~Ancient of War~Choose One": AncientofWar,
			"Classic~Mage~Minion~7~5~7~None~Archmage Antonidas~Legendary": ArchmageAntonidas,
			"Classic~Monk~Minion~7~7~7~None~Kun-Lai Summit Zen Alchemist": KunLaiSummitZenAlchemist,
			"Classic~Warlock~Minion~7~5~8~Demon~Siegebreaker~Taunt": Siegebreaker,
			},
			8: {
			"Basic~Druid~Minion~8~8~8~None~Ironbark Protector~Taunt": IronbarkProtector,
			"Classic~Neutral~Minion~8~5~5~Elemental~Arcane Devourer": ArcaneDevourer,
			"Classic~Neutral~Minion~8~7~7~None~Gruul~Legendary": Gruul,
			"Classic~Monk~Minion~8~6~10~None~Pandaria Guardian~Taunt~Quaff": PandariaGuardian,
			"Classic~Paladin~Minion~8~6~6~None~Tirion Fordring~Taunt~Divine Shield~Deathrattle~Legendary": TirionFordring,
			"Classic~Priest~Minion~8~8~1~None~Natalie Seline~Battlecry": NatalieSeline,
			"Classic~Shaman~Minion~8~3~5~Elemental~Al'Akir the Windlord~Taunt~Charge~Windfury~Divine Shield~Legendary": AlAkirtheWindlord,
			"Classic~Warrior~Minion~8~4~9~None~Grommash Hellscream~Charge~Legendary": GrommashHellscream,
			},
			0: {
			"Classic~Neutral~Minion~0~1~1~None~Wisp": Wisp,
			},
			9: {
			"Classic~Neutral~Minion~9~8~8~Dragon~Alexstrasza~Battlecry~Legendary": Alexstrasza,
			"Classic~Neutral~Minion~9~4~12~Dragon~Malygos~Spell Damage~Legendary": Malygos,
			"Classic~Neutral~Minion~9~8~8~Dragon~Nozdormu~Legendary": Nozdormu,
			"Classic~Neutral~Minion~9~8~8~Dragon~Onyxia~Battlecry~Legendary": Onyxia,
			"Classic~Neutral~Minion~9~4~12~Dragon~Ysera~Legendary": Ysera,
			"Classic~Druid~Minion~9~5~8~None~Cenarius~Choose One~Legendary": Cenarius,
			"Classic~Hunter~Minion~9~8~8~Beast~King Krush~Charge~Legendary": KingKrush,
			"Classic~Monk~Minion~9~4~12~None~Monk Dragon Keeper~Rush~Windfury~Quaff": MonkDragonKeeper,
			"Classic~Warlock~Minion~9~3~15~Demon~Lord Jaraxxus~Battlecry~Legendary": LordJaraxxus,
			},
			10: {
			"Classic~Neutral~Minion~10~12~12~Dragon~Deathwing~Battlecry~Legendary": Deathwing,
			"Classic~Neutral~Minion~10~8~8~None~Sea Giant": SeaGiant,
			},
		}
ClassCards = {
			'Demon Hunter': {
				"Basic~Demon Hunter~Minion~1~2~1~Demon~Shadowhoof Slayer~Battlecry": ShadowhoofSlayer,
				"Basic~Demon Hunter~Spell~2~Chaos Strike": ChaosStrike,
				"Basic~Demon Hunter~Minion~2~3~2~Demon~Sightless Watcher~Battlecry": SightlessWatcher,
				"Basic~Demon Hunter~Weapon~3~2~2~Aldrachi Warblades~Lifesteal": AldrachiWarblades,
				"Basic~Demon Hunter~Spell~3~Coordinated Strike": CoordinatedStrike,
				"Basic~Demon Hunter~Minion~3~4~2~Demon~Satyr Overseer": SatyrOverseer,
				"Basic~Demon Hunter~Spell~3~Soul Cleave": SoulCleave,
				"Basic~Demon Hunter~Spell~5~Chaos Nova": ChaosNova,
				"Basic~Demon Hunter~Minion~5~7~4~None~Glaivebound Adept~Battlecry": GlaiveboundAdept,
				"Basic~Demon Hunter~Spell~8~Inner Demon": InnerDemon,
			},
			'Druid': {
				"Basic~Druid~Spell~0~Innervate": Innervate,
				"Basic~Druid~Spell~0~Moonfire": Moonfire,
				"Basic~Druid~Spell~1~Claw": Claw,
				"Basic~Druid~Spell~2~Mark of the Wild": MarkoftheWild,
				"Basic~Druid~Spell~3~Healing Touch": HealingTouch,
				"Basic~Druid~Spell~3~Savage Roar": SavageRoar,
				"Basic~Druid~Spell~3~Wild Growth": WildGrowth,
				"Basic~Druid~Spell~4~Swipe": Swipe,
				"Basic~Druid~Spell~6~Starfire": Starfire,
				"Basic~Druid~Minion~8~8~8~None~Ironbark Protector~Taunt": IronbarkProtector,
				"Classic~Druid~Spell~1~Savagery": Savagery,
				"Classic~Druid~Spell~2~Power of the Wild~Choose One": PoweroftheWild,
				"Classic~Druid~Spell~2~Wrath~Choose One": Wrath,
				"Classic~Druid~Spell~3~Mark of Nature~Choose One": MarkofNature,
				"Classic~Druid~Spell~4~Bite": Bite,
				"Classic~Druid~Minion~4~2~2~None~Keeper of the Grove~Choose One": KeeperoftheGrove,
				"Classic~Druid~Spell~4~Soul of the Forest": SouloftheForest,
				"Classic~Druid~Minion~5~4~4~None~Druid of the Claw~Choose One": DruidoftheClaw,
				"Classic~Druid~Spell~5~Force of Nature": ForceofNature,
				"Classic~Druid~Spell~5~Starfall~Choose One": Starfall,
				"Classic~Druid~Spell~6~Nourish~Choose One": Nourish,
				"Classic~Druid~Minion~7~5~5~None~Ancient of Lore~Choose One": AncientofLore,
				"Classic~Druid~Minion~7~5~5~None~Ancient of War~Choose One": AncientofWar,
				"Classic~Druid~Spell~8~Gift of the Wild": GiftoftheWild,
				"Classic~Druid~Minion~9~5~8~None~Cenarius~Choose One~Legendary": Cenarius,
			},
			'Hunter': {
				"Basic~Hunter~Spell~1~Arcane Shot": ArcaneShot,
				"Basic~Hunter~Minion~1~1~1~Beast~Timber Wolf": TimberWolf,
				"Basic~Hunter~Spell~1~Tracking": Tracking,
				"Basic~Hunter~Spell~2~Hunter's Mark": HuntersMark,
				"Basic~Hunter~Spell~3~Animal Companion": AnimalCompanion,
				"Basic~Hunter~Spell~3~Kill Command": KillCommand,
				"Basic~Hunter~Minion~4~4~3~None~Houndmaster~Battlecry": Houndmaster,
				"Basic~Hunter~Spell~4~Multi Shot": MultiShot,
				"Basic~Hunter~Minion~5~3~2~Beast~Starving Buzzard": StarvingBuzzard,
				"Basic~Hunter~Minion~5~2~5~Beast~Tundra Rhino": TundraRhino,
				"Classic~Hunter~Spell~1~Bestial Wrath": BestialWrath,
				"Classic~Hunter~Spell~2~Explosive Trap~~Secret": ExplosiveTrap,
				"Classic~Hunter~Spell~2~Freezing Trap~~Secret": FreezingTrap,
				"Classic~Hunter~Spell~2~Misdirection~~Secret": Misdirection,
				"Classic~Hunter~Spell~2~Snake Trap~~Secret": SnakeTrap,
				"Classic~Hunter~Spell~2~Snipe~~Secret": Snipe,
				"Classic~Hunter~Spell~2~Flare": Flare,
				"Classic~Hunter~Minion~2~2~2~Beast~Scavenging Hyena": ScavengingHyena,
				"Classic~Hunter~Spell~3~Deadly Shot": DeadlyShot,
				"Classic~Hunter~Weapon~3~3~2~Eaglehorn Bow": EaglehornBow,
				"Classic~Hunter~Spell~3~Unleash the Hounds": UnleashtheHounds,
				"Classic~Hunter~Spell~5~Explosive Shot": ExplosiveShot,
				"Classic~Hunter~Minion~6~6~5~Beast~Savannah Highmane~Deathrattle": SavannahHighmane,
				"Classic~Hunter~Weapon~7~5~2~Gladiator's Longbow": GladiatorsLongbow,
				"Classic~Hunter~Minion~9~8~8~Beast~King Krush~Charge~Legendary": KingKrush,
			},
			'Mage': {
				"Basic~Mage~Spell~1~Arcane Missiles": ArcaneMissiles,
				"Basic~Mage~Spell~1~Mirror Image": MirrorImage,
				"Basic~Mage~Spell~2~Arcane Explosion": ArcaneExplosion,
				"Basic~Mage~Spell~2~Frostbolt": Frostbolt,
				"Basic~Mage~Spell~3~Arcane Intellect": ArcaneIntellect,
				"Basic~Mage~Spell~3~Frost Nova": FrostNova,
				"Basic~Mage~Spell~4~Fireball": Fireball,
				"Basic~Mage~Spell~4~Polymorph": Polymorph,
				"Basic~Mage~Minion~4~3~6~Elemental~Water Elemental": WaterElemental,
				"Basic~Mage~Spell~7~Flamestrike": Flamestrike,
				"Classic~Mage~Spell~1~Tome of Intellect": TomeofIntellect,
				"Classic~Mage~Spell~2~Icicle": Icicle,
				"Classic~Mage~Minion~2~1~3~None~Mana Wyrm": ManaWyrm,
				"Classic~Mage~Minion~2~3~2~None~Sorcerer's Apprentice": SorcerersApprentice,
				"Classic~Mage~Spell~3~Counterspell~~Secret": Counterspell,
				"Classic~Mage~Spell~3~Ice Barrier~~Secret": IceBarrier,
				"Classic~Mage~Spell~3~Mirror Entity~~Secret": MirrorEntity,
				"Classic~Mage~Spell~3~Spellbender~~Secret": Spellbender,
				"Classic~Mage~Spell~3~Vaporize~~Secret": Vaporize,
				"Classic~Mage~Minion~3~4~3~None~Kirin Tor Mage~Battlecry": KirinTorMage,
				"Classic~Mage~Spell~4~Cone of Cold": ConeofCold,
				"Classic~Mage~Minion~4~3~3~None~Ethereal Arcanist": EtherealArcanist,
				"Classic~Mage~Spell~6~Blizzard": Blizzard,
				"Classic~Mage~Minion~7~5~7~None~Archmage Antonidas~Legendary": ArchmageAntonidas,
				"Classic~Mage~Spell~10~Pyroblast": Pyroblast,
			},
			'Monk': {
				"Basic~Monk~Spell~0~Resuscitate": Resuscitate,
				"Basic~Monk~Minion~1~0~2~None~Arch of the Temple~Taunt~Battlecry": ArchoftheTemple,
				"Basic~Monk~Weapon~1~0~4~Cane with a Wine Gourd": CanewithaWineGourd,
				"Basic~Monk~Minion~1~1~3~None~Monk's Apprentice": MonksApprentice,
				"Basic~Monk~Spell~1~Shaohao's Protection": ShaohaosProtection,
				"Basic~Monk~Spell~2~Effusive Mists": EffusiveMists,
				"Basic~Monk~Minion~2~1~4~None~Swift Brewmaster": SwiftBrewmaster,
				"Basic~Monk~Spell~3~Provoke": Provoke,
				"Basic~Monk~Minion~3~1~4~None~Sweeping Kick Fighter~Rush": SweepingKickFighter,
				"Basic~Monk~Minion~3~3~4~None~Shado-Pan Wu Kao": ShadoPanWuKao,
				"Classic~Monk~Minion~1~0~4~None~Wise Lorewalker Cho~Battlecry~Legendary": WiseLorewalkerCho,
				"Classic~Monk~Minion~1~1~1~Beast~Xuen, the White Tiger~Rush~Legendary": XuentheWhiteTiger_Mutable_1,
				"Classic~Monk~Minion~2~2~3~None~Defense Technique Master~Taunt~Quaff": DefenseTechniqueMaster,
				"Classic~Monk~Spell~2~Transcendance": Transcendance,
				"Classic~Monk~Spell~2~Purifying Brew~Quaff": PurifyingBrew,
				"Classic~Monk~Spell~3~Liquor~Quaff": Liquor,
				"Classic~Monk~Spell~3~Stave Off": StaveOff,
				"Classic~Monk~Spell~3~Touch of Karma": TouchofKarma,
				"Classic~Monk~Spell~3~Spirit Tether": SpiritTether,
				"Classic~Monk~Spell~4~Drunken Boxing": DrunkenBoxing,
				"Classic~Monk~Minion~4~5~4~Monk~Onima Actuary~Stealth": OnimaActuary,
				"Classic~Monk~Minion~5~3~5~Beast~Spawn of Xuen~Rush~Battlecry": SpawnofXuen,
				"Classic~Monk~Spell~5~Quick Sip~Quaff": QuickSip,
				"Classic~Monk~Minion~4~5~3~None~Pawn of Shaohao~Rush~Windfury": PawnofShaohao,
				"Classic~Monk~Minion~4~3~5~None~Shaohao, the Emperor~Battlecry~Legendary": ShaohaotheEmperor,
				"Classic~Monk~Spell~6~Inner Peace": InnerPeace,
				"Classic~Monk~Minion~6~3~7~None~Lotus Healer~Taunt": LotusHealer,
				"Classic~Monk~Spell~6~Rushing Jade Wind": RushingJadeWind,
				"Classic~Monk~Minion~7~7~7~None~Kun-Lai Summit Zen Alchemist": KunLaiSummitZenAlchemist,
				"Classic~Monk~Weapon~8~2~4~Fists of the Heavens~Windfury": FistsoftheHeavens,
				"Classic~Monk~Minion~8~6~10~None~Pandaria Guardian~Taunt~Quaff": PandariaGuardian,
				"Classic~Monk~Minion~9~4~12~None~Monk Dragon Keeper~Rush~Windfury~Quaff": MonkDragonKeeper,
			},
			'Paladin': {
				"Basic~Paladin~Spell~1~Blessing of Might": BlessingofMight,
				"Basic~Paladin~Spell~1~Hand of Protection": HandofProtection,
				"Basic~Paladin~Spell~1~Humility": Humility,
				"Basic~Paladin~Weapon~1~1~4~Light's Justice": LightsJustice,
				"Basic~Paladin~Spell~2~Holy Light": HolyLight,
				"Basic~Paladin~Spell~4~Blessing of Kings": BlessingofKings,
				"Basic~Paladin~Spell~4~Consecration": Consecration,
				"Basic~Paladin~Spell~4~Hammer of Wrath": HammerofWrath,
				"Basic~Paladin~Weapon~4~4~2~Truesilver Champion": TruesilverChampion,
				"Basic~Paladin~Minion~7~5~6~None~Guardian of Kings~Battlecry": GuardianofKings,
				"Classic~Paladin~Spell~1~Blessing of Wisdom": BlessingofWisdom,
				"Classic~Paladin~Spell~1~Eye for an Eye~~Secret": EyeforanEye,
				"Classic~Paladin~Spell~1~Noble Sacrifice~~Secret": NobleSacrifice,
				"Classic~Paladin~Spell~1~Redemption~~Secret": Redemption,
				"Classic~Paladin~Spell~1~Repentance~~Secret": Repentance,
				"Classic~Paladin~Minion~2~2~2~None~Argent Protector~Battlecry": ArgentProtector,
				"Classic~Paladin~Spell~4~Equality": Equality,
				"Classic~Paladin~Minion~3~3~3~None~Ardor Peacekeeper~Battlecry": AldorPeacekeeper,
				"Classic~Paladin~Weapon~3~1~5~Sword of Justice": SwordofJustice,
				"Classic~Paladin~Spell~5~Blessed Champion": BlessedChampion,
				"Classic~Paladin~Spell~5~Holy Wrath": HolyWrath,
				"Classic~Paladin~Spell~5~Righteousness": Righteousness,
				"Classic~Paladin~Spell~6~Avenging Wrath": AvengingWrath,
				"Classic~Paladin~Spell~8~Lay on Hands": LayonHands,
				"Classic~Paladin~Minion~8~6~6~None~Tirion Fordring~Taunt~Divine Shield~Deathrattle~Legendary": TirionFordring,
			},
			'Priest': {
				"Basic~Priest~Spell~0~Power Word: Shield": PowerWordShield,
				"Basic~Priest~Spell~1~Holy Smite": HolySmite,
				"Basic~Priest~Spell~1~Mind Vision": MindVision,
				"Basic~Priest~Minion~1~1~1~None~Psychic Conjurer-Battlecry": PsychicConjurer,
				"Basic~Priest~Spell~1~Radiance": Radiance,
				"Basic~Priest~Spell~2~Shadow Word: Death": ShadowWordDeath,
				"Basic~Priest~Spell~2~Shadow Word: Pain": ShadowWordPain,
				"Basic~Priest~Spell~4~Holy Nova": HolyNova,
				"Basic~Priest~Spell~4~Power Infusion": PowerInfusion,
				"Basic~Priest~Spell~10~Mind Control": MindControl,
				"Classic~Priest~Spell~0~Circle of Healing": CircleofHealing,
				"Classic~Priest~Spell~0~Silence": Silence,
				"Classic~Priest~Spell~1~Inner Fire": InnerFire,
				"Classic~Priest~Minion~1~2~1~None~Scarlet Subjugator~Battlecry": ScarletSubjugator,
				"Classic~Priest~Minion~2~2~3~None~Kul Tiran Chaplain~Battlecry": KulTiranChaplain,
				"Classic~Priest~Minion~2~0~5~None~Lightwell": Lightwell,
				"Classic~Priest~Spell~2~Thoughtsteal": Thoughtsteal,
				"Classic~Priest~Spell~3~Shadow Madness": ShadowMadness,
				"Classic~Priest~Minion~4~0~5~None~Lightspawn": Lightspawn,
				"Classic~Priest~Spell~4~Mass Dispel": MassDispel,
				"Classic~Priest~Spell~4~Mindgames": Mindgames,
				"Classic~Priest~Spell~4~Shadow Word: Ruin": ShadowWordRuin,
				"Classic~Priest~Minion~6~4~5~None~Cabal Shadow Priest~Battlecry": CabalShadowPriest,
				"Classic~Priest~Minion~5~5~6~None~Temple Enforcer~Battlecry": TempleEnforcer,
				"Classic~Priest~Minion~8~8~1~None~Natalie Seline~Battlecry": NatalieSeline,
			},
			'Rogue': {
				"Basic~Rogue~Spell~0~Backstab": Backstab,
				"Basic~Rogue~Spell~1~Deadly Poison": DeadlyPoison,
				"Basic~Rogue~Spell~1~Sinister Strike": SinisterStrike,
				"Basic~Rogue~Spell~2~Sap": Sap,
				"Basic~Rogue~Spell~2~Shiv": Shiv,
				"Basic~Rogue~Spell~3~Fan of Knives": FanofKnives,
				"Basic~Rogue~Minion~4~3~3~None~Plaguebringer~Battlecry": Plaguebringer,
				"Basic~Rogue~Spell~5~Assassinate": Assassinate,
				"Basic~Rogue~Weapon~5~3~4~Assassin's Blade": AssassinsBlade,
				"Basic~Rogue~Spell~7~Sprint": Sprint,
				"Classic~Rogue~Spell~0~Preparation": Preparation,
				"Classic~Rogue~Spell~0~Shadowstep": Shadowstep,
				"Classic~Rogue~Spell~1~Pilfer": Pilfer,
				"Classic~Rogue~Spell~2~Betrayal": Betrayal,
				"Classic~Rogue~Spell~2~Cold Blood~Combo": ColdBlood,
				"Classic~Rogue~Minion~2~2~2~None~Defias Ringleader~Combo": DefiasRingleader,
				"Classic~Rogue~Spell~2~Eviscerate~Combo": Eviscerate,
				"Classic~Rogue~Minion~2~1~1~None~Patient Assassin~Poisonous~Stealth": PatientAssassin,
				"Classic~Rogue~Minion~3~2~2~None~Edwin VanCleef~Combo~Legendary": EdwinVanCleef,
				"Classic~Rogue~Spell~3~Headcrack~Combo": Headcrack,
				"Classic~Rogue~Weapon~3~2~2~Perdition's Blade~Combo~Battlecry": PerditionsBlade,
				"Classic~Rogue~Minion~3~3~3~None~SI:7 Agent~Combo": SI7Agent,
				"Classic~Rogue~Spell~4~Blade Flurry": BladeFlurry,
				"Classic~Rogue~Minion~4~4~4~None~Master of Disguise~Battlecry": MasterofDisguise,
				"Classic~Rogue~Minion~6~5~3~None~Kidnapper~Combo": Kidnapper,
			},
			'Shaman': {
				"Basic~Shaman~Spell~0~Ancestral Healing": AncestralHealing,
				"Basic~Shaman~Spell~0~Totemic Might": TotemicMight,
				"Basic~Shaman~Spell~1~Frost Shock": FrostShock,
				"Basic~Shaman~Spell~2~Rockbiter Weapon": RockbiterWeapon,
				"Basic~Shaman~Spell~2~Windfury": Windfury,
				"Basic~Shaman~Minion~3~0~3~Totem~Flametongue Totem": FlametongueTotem,
				"Basic~Shaman~Spell~4~Hex": Hex,
				"Basic~Shaman~Minion~4~3~3~None~Windspeaker~Battlecry": Windspeaker,
				"Basic~Shaman~Spell~5~Bloodlust": Bloodlust,
				"Basic~Shaman~Minion~6~6~5~Elemental~Fire Elemental~Battlecry": FireElemental,
				"Classic~Shaman~Minion~1~3~1~Elemental~Dust Devil~Overload~Windfury": DustDevil,
				"Classic~Shaman~Spell~1~Earth Shock": EarthShock,
				"Classic~Shaman~Spell~1~Forked Lightning~Overload": ForkedLightning,
				"Classic~Shaman~Spell~1~Lightning Bolt~Overload": LightningBolt,
				"Classic~Shaman~Spell~2~Ancestral Spirit": AncestralSpirit,
				"Classic~Shaman~Weapon~2~2~3~Stormforged Axe~Overload": StormforgedAxe,
				"Classic~Shaman~Spell~3~Far Sight": FarSight,
				"Classic~Shaman~Spell~3~Feral Spirit~Overload": FeralSpirit,
				"Classic~Shaman~Spell~3~Lava Burst~Overload": LavaBurst,
				"Classic~Shaman~Spell~3~Lightning Storm~Overload": LightningStorm,
				"Classic~Shaman~Minion~3~0~3~Totem~Mana Tide Totem": ManaTideTotem,
				"Classic~Shaman~Minion~3~2~4~Elemental~Unbound Elemental": UnboundElemental,
				"Classic~Shaman~Weapon~5~2~8~Doomhammer~Windfury~Overload": Doomhammer,
				"Classic~Shaman~Minion~5~7~8~Elemental~Earth Elemental~Taunt~Overload": EarthElemental,
				"Classic~Shaman~Minion~8~3~5~Elemental~Al'Akir the Windlord~Taunt~Charge~Windfury~Divine Shield~Legendary": AlAkirtheWindlord,
			},
			'Warlock': {
				"Basic~Warlock~Spell~0~Sacrificial Pact": SacrificialPact,
				"Basic~Warlock~Spell~1~Corruption": Corruption,
				"Basic~Warlock~Spell~1~Mortal Coil": MortalCoil,
				"Basic~Warlock~Spell~1~Soulfire": Soulfire,
				"Basic~Warlock~Minion~1~1~3~Demon~Voidwalker~Taunt": Voidwalker,
				"Basic~Warlock~Minion~2~4~3~Demon~Felstalker~Battlecry": Felstalker,
				"Basic~Warlock~Spell~3~Drain Life": DrainLife,
				"Basic~Warlock~Spell~3~Shadow Bolt": ShadowBolt,
				"Basic~Warlock~Spell~4~Hellfire": Hellfire,
				"Basic~Warlock~Minion~6~6~6~Demon~Dread Infernal~Battlecry": DreadInfernal,
				"Classic~Warlock~Minion~1~0~1~Demon~Blood Imp~Stealth": BloodImp,
				"Classic~Warlock~Spell~1~Call of the Void": CalloftheVoid,
				"Classic~Warlock~Minion~1~3~2~Demon~Flame Imp~Battlecry": FlameImp,
				"Classic~Warlock~Spell~2~Demonfire": Demonfire,
				"Classic~Warlock~Spell~3~Sense Demons": SenseDemons,
				"Classic~Warlock~Minion~4~0~4~None~Summoning Portal": SummoningPortal,
				"Classic~Warlock~Minion~3~3~5~Demon~Felguard~Taunt~Battlecry": Felguard,
				"Classic~Warlock~Minion~3~3~3~Demon~Void Terror~Battlecry": VoidTerror,
				"Classic~Warlock~Minion~4~5~6~Demon~Pit Lord~Battlecry": PitLord,
				"Classic~Warlock~Spell~4~Shadowflame": Shadowflame,
				"Classic~Warlock~Spell~5~Bane of Doom": BaneofDoom,
				"Classic~Warlock~Spell~6~Siphon Soul": SiphonSoul,
				"Classic~Warlock~Minion~7~5~8~Demon~Siegebreaker~Taunt": Siegebreaker,
				"Classic~Warlock~Spell~8~Twisting Nether": TwistingNether,
				"Classic~Warlock~Minion~9~3~15~Demon~Lord Jaraxxus~Battlecry~Legendary": LordJaraxxus,
			},
			'Warrior': {
				"Basic~Warrior~Spell~1~Whirlwind": Whirlwind,
				"Basic~Warrior~Spell~1~Charge": Charge,
				"Basic~Warrior~Spell~2~Execute": Execute,
				"Basic~Warrior~Spell~2~Cleave": Cleave,
				"Basic~Warrior~Spell~2~Heroic Strike": HeroicStrike,
				"Basic~Warrior~Weapon~3~3~2~Fiery War Axe": FieryWarAxe,
				"Basic~Warrior~Spell~3~Shield Block": ShieldBlock,
				"Basic~Warrior~Minion~3~2~3~None~Warsong Commander": WarsongCommander,
				"Basic~Warrior~Minion~4~4~3~None~Kor'kron Elite~Charge": KorkronElite,
				"Basic~Warrior~Weapon~5~5~2~Arcanite Reaper": ArcaniteReaper,
				"Classic~Warrior~Spell~0~Inner Rage": InnerRage,
				"Classic~Warrior~Spell~1~Shield Slam": ShieldSlam,
				"Classic~Warrior~Spell~1~Upgrade!": Upgrade,
				"Classic~Warrior~Minion~2~1~4~None~Armorsmith": Armorsmith,
				"Classic~Warrior~Spell~2~Battle Rage": BattleRage,
				"Classic~Warrior~Spell~2~Commanding Shout": CommandingShout,
				"Classic~Warrior~Minion~2~2~2~None~Cruel Taskmaster~Battlecry": CruelTaskmaster,
				"Classic~Warrior~Spell~2~Rampage": Rampage,
				"Classic~Warrior~Spell~2~Slam": Slam,
				"Classic~Warrior~Minion~3~2~4~None~Frothing Berserker": FrothingBerserker,
				"Classic~Warrior~Minion~4~3~3~None~Arathi Weaponsmith~Battlecry": ArathiWeaponsmith,
				"Classic~Warrior~Spell~4~Mortal Strike": MortalStrike,
				"Classic~Warrior~Spell~5~Brawl": Brawl,
				"Classic~Warrior~Weapon~7~7~1~Gorehowl": Gorehowl,
				"Classic~Warrior~Minion~8~4~9~None~Grommash Hellscream~Charge~Legendary": GrommashHellscream,
			},
			}

NeutralMinions = {
			"Basic~Neutral~Minion~1~1~1~None~Elven Archer~Battlecry": ElvenArcher,
			"Basic~Neutral~Minion~1~1~2~None~Goldshire Footman~Taunt": GoldshireFootman,
			"Basic~Neutral~Minion~1~1~1~Murloc~Grimscale Oracle": GrimscaleOracle,
			"Basic~Neutral~Minion~1~2~1~Murloc~Murloc Raider": MurlocRaider,
			"Basic~Neutral~Minion~1~1~1~Beast~Stonetusk Boar~Charge": StonetuskBoar,
			"Basic~Neutral~Minion~1~2~1~None~Voodoo Doctor~Battlecry": VoodooDoctor,
			"Basic~Neutral~Minion~2~3~2~None~Acidic Swamp Ooze~Battlecry": AcidicSwampOoze,
			"Basic~Neutral~Minion~2~3~2~Beast~Bloodfen Raptor": BloodfenRaptor,
			"Basic~Neutral~Minion~2~2~1~Murloc~Bluegill Warrior~Charge": BluegillWarrior,
			"Basic~Neutral~Minion~2~2~2~None~Frostwolf Grunt~Taunt": FrostwolfGrunt,
			"Basic~Neutral~Minion~2~2~2~None~Kobold Geomancer~Spell Damage": KoboldGeomancer,
			"Basic~Neutral~Minion~2~2~1~Murloc~Murloc Tidehunter~Battlecry": MurlocTidehunter,
			"Basic~Neutral~Minion~2~1~1~None~Novice Engineer~Battlecry": NoviceEngineer,
			"Basic~Neutral~Minion~2~2~3~Beast~River Crocolisk": RiverCrocolisk,
			"Basic~Neutral~Minion~3~1~4~None~Dalaran Mage~Spell Damage": DalaranMage,
			"Basic~Neutral~Minion~3~2~2~None~Ironforge Rifleman~Battlecry": IronforgeRifleman,
			"Basic~Neutral~Minion~3~3~3~Beast~Ironfur Grizzly~Taunt": IronfurGrizzly,
			"Basic~Neutral~Minion~3~5~1~Elemental~Magma Rager": MagmaRager,
			"Basic~Neutral~Minion~3~2~2~None~Raid Leader": RaidLeader,
			"Basic~Neutral~Minion~3~2~3~None~Razorfen Hunter~Battlecry": RazorfenHunter,
			"Basic~Neutral~Minion~3~3~2~None~Shattered Sun Cleric~Battlecry": ShatteredSunCleric,
			"Basic~Neutral~Minion~3~1~4~Beast~Silverback Patriarch~Taunt": SilverbackPatriarch,
			"Basic~Neutral~Minion~3~3~1~None~Wolfrider~Charge": Wolfrider,
			"Basic~Neutral~Minion~4~4~5~None~Chillwind Yeti": ChillwindYeti,
			"Basic~Neutral~Minion~4~2~4~None~Dragonling Mechanic~Battlecry": DragonlingMechanic,
			"Basic~Neutral~Minion~4~2~4~None~Gnomish Inventor~Battlecry": GnomishInventor,
			"Basic~Neutral~Minion~4~2~7~Beast~Oasis Snapjaw": OasisSnapjaw,
			"Basic~Neutral~Minion~4~4~4~None~Ogre Magi~Spell Damage": OgreMagi,
			"Basic~Neutral~Minion~4~3~5~None~Sen'jin Shieldmasta~Taunt": SenjinShieldmasta,
			"Basic~Neutral~Minion~4~2~5~None~Stormwind Knight~Charge": StormwindKnight,
			"Basic~Neutral~Minion~5~5~4~None~Booty Bay Bodyguard~Taunt": BootyBayBodyguard,
			"Basic~Neutral~Minion~5~4~5~None~Darkscale Healer~Battlecry": DarkscaleHealer,
			"Basic~Neutral~Minion~5~4~4~None~Frostwolf Warlord~Battlecry": FrostwolfWarlord,
			"Basic~Neutral~Minion~5~2~7~None~Gurubashi Berserker": GurubashiBerserker,
			"Basic~Neutral~Minion~5~4~4~None~Nightblade~Battlecry": Nightblade,
			"Basic~Neutral~Minion~5~4~2~None~Stormpike Commando~Battlecry": StormpikeCommando,
			"Basic~Neutral~Minion~6~6~5~None~Lord of the Arena~Taunt": LordoftheArena,
			"Basic~Neutral~Minion~6~4~7~None~Archmage~Spell Damage": Archmage,
			"Basic~Neutral~Minion~6~6~7~None~Boulderfist Ogre": BoulderfistOgre,
			"Basic~Neutral~Minion~6~5~2~None~Reckless Rocketeer~Charge": RecklessRocketeer,
			"Basic~Neutral~Minion~7~9~5~Beast~Core Hound": CoreHound,
			"Basic~Neutral~Minion~7~6~6~None~Stormwind Champion": StormwindChampion,
			"Basic~Neutral~Minion~7~7~7~None~War Golem": WarGolem,
			"Classic~Neutral~Minion~0~1~1~None~Wisp": Wisp,
			"Classic~Neutral~Minion~1~1~1~None~Abusive Sergeant~Battlecry": AbusiveSergeant,
			"Classic~Neutral~Minion~1~1~1~None~Argent Squire~Divine Shield": ArgentSquire,
			"Classic~Neutral~Minion~1~1~1~Beast~Angry Chicken": AngryChicken,
			"Classic~Neutral~Minion~1~1~2~Pirate~Bloodsail Corsair~Battlecry": BloodsailCorsair,
			"Classic~Neutral~Minion~1~1~2~Beast~Hungry Crab~Battlecry": HungryCrab,
			"Classic~Neutral~Minion~1~1~1~None~Leper Gnome~Deathrattle": LeperGnome,
			"Classic~Neutral~Minion~1~1~2~None~Lightwarden": Lightwarden,
			"Classic~Neutral~Minion~1~1~2~Murloc~Murloc Tidecaller": MurlocTidecaller,
			"Classic~Neutral~Minion~1~1~2~None~Secretkeeper": Secretkeeper,
			"Classic~Neutral~Minion~1~0~4~None~Shieldbearer~Taunt": Shieldbearer,
			"Classic~Neutral~Minion~1~2~1~Pirate~Southsea Deckhand": SouthseaDeckhand,
			"Classic~Neutral~Minion~1~2~1~None~Worgen Infiltrator~Stealth": WorgenInfiltrator,
			"Classic~Neutral~Minion~1~1~1~Beast~Young Dragonhawk~Windfury": YoungDragonhawk,
			"Classic~Neutral~Minion~1~2~1~None~Young Priestess": YoungPriestess,
			"Classic~Neutral~Minion~2~2~3~None~Amani Berserker": AmaniBerserker,
			"Classic~Neutral~Minion~2~4~5~None~Ancient Watcher": AncientWatcher,
			"Classic~Neutral~Minion~2~1~1~None~Bloodmage Thalnos~Deathrattle~Spell Damage~Legendary": BloodmageThalnos,
			"Classic~Neutral~Minion~2~2~3~Pirate~Bloodsail Raider~Battlecry": BloodsailRaider,
			"Classic~Neutral~Minion~2~2~2~None~Crazed Alchemist~Battlecry": CrazedAlchemist,
			"Classic~Neutral~Minion~2~2~2~Beast~Dire Wolf Alpha": DireWolfAlpha,
			"Classic~Neutral~Minion~2~0~7~None~Doomsayer": Doomsayer,
			"Classic~Neutral~Minion~2~3~2~Dragon~Faerie Dragon": FaerieDragon,
			"Classic~Neutral~Minion~2~2~2~None~Knife Juggler": KnifeJuggler,
			"Classic~Neutral~Minion~2~2~1~None~Loot Hoarder~Deathrattle": LootHoarder,
			"Classic~Neutral~Minion~2~0~4~None~Lorewalker Cho~Legendary": LorewalkerCho,
			"Classic~Neutral~Minion~2~3~2~None~Mad Bomber~Battlecry": MadBomber,
			"Classic~Neutral~Minion~2~1~3~None~Mana Addict": ManaAddict,
			"Classic~Neutral~Minion~2~2~2~None~Mana Wraith": ManaWraith,
			"Classic~Neutral~Minion~2~1~3~None~Master Swordsmith": MasterSwordsmith,
			"Classic~Neutral~Minion~2~4~4~None~Millhouse Manastorm~Battlecry~Legendary": MillhouseManastorm,
			"Classic~Neutral~Minion~2~0~4~None~Nat Pagle~Legendary": NatPagle,
			"Classic~Neutral~Minion~2~2~2~None~Pint-Sized Summoner": PintSizedSummoner,
			"Classic~Neutral~Minion~2~2~3~None~Sunfury Protector~Battlecry": SunfuryProtector,
			"Classic~Neutral~Minion~2~3~2~None~Wild Pyromancer": WildPyromancer,
			"Classic~Neutral~Minion~2~3~2~None~Youthful Brewmaster~Battlecry": YouthfulBrewmaster,
			"Classic~Neutral~Minion~3~0~3~Mech~Alarm-o-Bot": AlarmoBot,
			"Classic~Neutral~Minion~3~4~4~None~Arcane Golem~Battlecry": ArcaneGolem,
			"Classic~Neutral~Minion~3~3~3~None~Blood Knight~Battlecry": BloodKnight,
			"Classic~Neutral~Minion~3~3~2~Dragon~Brightwing~Battlecry~Legendary": Brightwing,
			"Classic~Neutral~Minion~3~2~3~Murloc~Coldlight Seer~Battlecry": ColdlightSeer,
			"Classic~Neutral~Minion~3~1~4~Mech~Demolisher": Demolisher,
			"Classic~Neutral~Minion~3~3~3~None~Earthen Ring Farseer~Battlecry": EarthenRingFarseer,
			"Classic~Neutral~Minion~3~2~3~Beast~Emperor Cobra~Poisonous": EmperorCobra,
			"Classic~Neutral~Minion~3~2~3~None~Flesheating Ghoul": FlesheatingGhoul,
			"Classic~Neutral~Minion~3~2~3~Mech~Harvest Golem~Deathrattle": HarvestGolem,
			"Classic~Neutral~Minion~3~1~5~None~Imp Master": ImpMaster,
			"Classic~Neutral~Minion~3~4~7~None~Injured Blademaster~Battlecry": InjuredBlademaster,
			"Classic~Neutral~Minion~3~2~1~Beast~Ironbeak Owl~Battlecry": IronbeakOwl,
			"Classic~Neutral~Minion~3~4~2~Beast~Jungle Panther~Stealth": JunglePanther,
			"Classic~Neutral~Minion~3~5~5~Beast~King Mukla~Battlecry~Legendary": KingMukla,
			"Classic~Neutral~Minion~3~3~3~Murloc~Murloc Warleader": MurlocWarleader,
			"Classic~Neutral~Minion~3~2~2~None~Questing Adventurer": QuestingAdventurer,
			"Classic~Neutral~Minion~3~3~3~None~Raging Worgen": RagingWorgen,
			"Classic~Neutral~Minion~3~3~1~None~Scarlet Crusader~Divine Shield": ScarletCrusader,
			"Classic~Neutral~Minion~3~3~3~Pirate~Southsea Captain": SouthseaCaptain,
			"Classic~Neutral~Minion~3~2~3~None~Tauren Warrior~Taunt": TaurenWarrior,
			"Classic~Neutral~Minion~3~2~3~None~Thrallmar Farseer~Windfury": ThrallmarFarseer,
			"Classic~Neutral~Minion~3~3~3~None~Tinkmaster Overspark~Battlecry~Legendary": TinkmasterOverspark,
			"Classic~Neutral~Minion~4~5~4~None~Ancient Brewmaster~Battlecry": AncientBrewmaster,
			"Classic~Neutral~Minion~4~2~5~None~Ancient Mage~Battlecry": AncientMage,
			"Classic~Neutral~Minion~4~4~2~None~Cult Master": CultMaster,
			"Classic~Neutral~Minion~4~4~4~None~Dark Iron Dwarf~Battlecry": DarkIronDwarf,
			"Classic~Neutral~Minion~4~2~3~None~Defender of Argus~Battlecry": DefenderofArgus,
			"Classic~Neutral~Minion~4~3~3~Pirate~Dread Corsair~Taunt": DreadCorsair,
			"Classic~Neutral~Minion~4~1~7~None~Mogu'shan Warden~Taunt": MogushanWarden,
			"Classic~Neutral~Minion~4~3~3~None~Silvermoon Guardian~Divine Shield": SilvermoonGuardian,
			"Classic~Neutral~Minion~4~5~4~None~SI:7 Infiltrator~Battlecry": SI7Infiltrator,
			"Classic~Neutral~Minion~4~4~1~Dragon~Twilight Drake~Battlecry": TwilightDrake,
			"Classic~Neutral~Minion~4~3~5~None~Violet Teacher": VioletTeacher,
			"Classic~Neutral~Minion~5~4~4~None~Abomination~Taunt~Deathrattle": Abomination,
			"Classic~Neutral~Minion~5~4~2~None~Big Game Hunter~Battlecry": BigGameHunter,
			"Classic~Neutral~Minion~5~5~4~Pirate~Captain Greenskin~Battlecry~Legendary": CaptainGreenskin,
			"Classic~Neutral~Minion~5~3~3~None~Faceless Manipulator~Battlecry": FacelessManipulator,
			"Classic~Neutral~Minion~5~3~6~None~Fen Creeper~Taunt": FenCreeper,
			"Classic~Neutral~Minion~5~5~4~None~Harrison Jones~Battlecry~Legendary": HarrisonJones,
			"Classic~Neutral~Minion~5~4~4~None~Silver Hand Knight~Battlecry": SilverHandKnight,
			"Classic~Neutral~Minion~5~4~6~None~Spiteful Smith": SpitefulSmith,
			"Classic~Neutral~Minion~5~3~5~Beast~Stampeding Kodo~Battlecry": StampedingKodo,
			"Classic~Neutral~Minion~5~5~5~Beast~Stranglethorn Tiger~Stealth": StranglethornTiger,
			"Classic~Neutral~Minion~5~7~6~None~Venture Co. Mercenary": VentureCoMercenary,
			"Classic~Neutral~Minion~6~4~2~None~Argent Commander~Divine Shield~Charge": ArgentCommander,
			"Classic~Neutral~Minion~6~4~5~None~Cairne Bloodhoof~Deathrattle~Legendary": CairneBloodhoof,
			"Classic~Neutral~Minion~6~5~5~Elemental~Frost Elemental~Battlecry": FrostElemental,
			"Classic~Neutral~Minion~6~4~4~None~Gadgetzan Auctioneer": GadgetzanAuctioneer,
			"Classic~Neutral~Minion~6~4~4~None~Hogger~Legendary": Hogger,
			"Classic~Neutral~Minion~6~7~5~Demon~Illidan Stormrage~Legendary": Xavius,
			"Classic~Neutral~Minion~6~5~4~None~Priestess of Elune~Battlecry": PriestessofElune,
			"Classic~Neutral~Minion~6~4~5~None~Sunwalker~Divine Shield~Taunt": Sunwalker,
			"Classic~Neutral~Minion~6~9~7~Beast~The Beast~Deathrattle~Legendary": TheBeast,
			"Classic~Neutral~Minion~6~4~5~None~The Black Knight~Battlecry~Legendary": TheBlackKnight,
			"Classic~Neutral~Minion~6~4~5~None~Windfury Harpy~Windfury": WindfuryHarpy,
			"Classic~Neutral~Minion~7~4~4~None~Barrens Stablehand~Battlecry": BarrensStablehand,
			"Classic~Neutral~Minion~7~7~5~Elemental~Baron Geddon~Legendary": BaronGeddon,
			"Classic~Neutral~Minion~7~6~8~None~High Inquisitor Whitemane~Battlecry~Legendary": HighInquisitorWhitemane,
			"Classic~Neutral~Minion~7~7~5~None~Ravenholdt Assassin~Stealth": RavenholdtAssassin,
			"Classic~Neutral~Minion~8~5~5~Elemental~Arcane Devourer": ArcaneDevourer,
			"Classic~Neutral~Minion~8~7~7~None~Gruul~Legendary": Gruul,
			"Classic~Neutral~Minion~9~8~8~Dragon~Alexstrasza~Battlecry~Legendary": Alexstrasza,
			"Classic~Neutral~Minion~9~4~12~Dragon~Malygos~Spell Damage~Legendary": Malygos,
			"Classic~Neutral~Minion~9~8~8~Dragon~Nozdormu~Legendary": Nozdormu,
			"Classic~Neutral~Minion~9~8~8~Dragon~Onyxia~Battlecry~Legendary": Onyxia,
			"Classic~Neutral~Minion~9~4~12~Dragon~Ysera~Legendary": Ysera,
			"Classic~Neutral~Minion~10~12~12~Dragon~Deathwing~Battlecry~Legendary": Deathwing,
			"Classic~Neutral~Minion~10~8~8~None~Sea Giant": SeaGiant,
		}

RNGPools = {
		'Legendary Minions': [BloodmageThalnos, LorewalkerCho, MillhouseManastorm, NatPagle, Brightwing, KingMukla, TinkmasterOverspark, CaptainGreenskin, HarrisonJones, CairneBloodhoof, 
				Hogger, Xavius, TheBeast, TheBlackKnight, BaronGeddon, HighInquisitorWhitemane, Gruul, Alexstrasza, Malygos, Nozdormu, 
				Onyxia, Ysera, Deathwing, Cenarius, KingKrush, ArchmageAntonidas, WiseLorewalkerCho, XuentheWhiteTiger_Mutable_1, ShaohaotheEmperor, TirionFordring, 
				EdwinVanCleef, AlAkirtheWindlord, LordJaraxxus, GrommashHellscream, ],
		'Beasts to Summon': [StonetuskBoar, BloodfenRaptor, RiverCrocolisk, IronfurGrizzly, SilverbackPatriarch, OasisSnapjaw, CoreHound, TimberWolf, StarvingBuzzard, TundraRhino, 
				AngryChicken, HungryCrab, YoungDragonhawk, DireWolfAlpha, EmperorCobra, IronbeakOwl, JunglePanther, KingMukla, StampedingKodo, StranglethornTiger, 
				TheBeast, ScavengingHyena, SavannahHighmane, KingKrush, XuentheWhiteTiger_Mutable_1, SpawnofXuen, ],
		'Mage Spells': [ArcaneMissiles, MirrorImage, ArcaneExplosion, Frostbolt, ArcaneIntellect, FrostNova, Fireball, Polymorph, Flamestrike, TomeofIntellect, 
				Icicle, Counterspell, IceBarrier, MirrorEntity, Spellbender, Vaporize, ConeofCold, Blizzard, Pyroblast, ],
		'0-Cost Spells': [Innervate, Moonfire, Resuscitate, PowerWordShield, CircleofHealing, Silence, Backstab, Preparation, Shadowstep, AncestralHealing, 
				TotemicMight, SacrificialPact, InnerRage, ],
		'1-Cost Spells': [Claw, Savagery, ArcaneShot, Tracking, BestialWrath, ArcaneMissiles, MirrorImage, TomeofIntellect, ShaohaosProtection, BlessingofMight, 
				HandofProtection, Humility, BlessingofWisdom, EyeforanEye, NobleSacrifice, Redemption, Repentance, HolySmite, MindVision, Radiance, 
				InnerFire, DeadlyPoison, SinisterStrike, Pilfer, FrostShock, EarthShock, ForkedLightning, LightningBolt, Corruption, MortalCoil, 
				Soulfire, CalloftheVoid, Whirlwind, Charge, ShieldSlam, Upgrade, ],
		'2-Cost Spells': [ChaosStrike, MarkoftheWild, PoweroftheWild, Wrath, HuntersMark, ExplosiveTrap, FreezingTrap, Misdirection, SnakeTrap, Snipe, 
				Flare, ArcaneExplosion, Frostbolt, Icicle, EffusiveMists, Transcendance, PurifyingBrew, HolyLight, ShadowWordDeath, ShadowWordPain, 
				Thoughtsteal, Sap, Shiv, Betrayal, ColdBlood, Eviscerate, RockbiterWeapon, Windfury, AncestralSpirit, Demonfire, 
				Execute, Cleave, HeroicStrike, BattleRage, CommandingShout, Rampage, Slam, ],
		'3-Cost Spells': [CoordinatedStrike, SoulCleave, HealingTouch, SavageRoar, WildGrowth, MarkofNature, AnimalCompanion, KillCommand, DeadlyShot, UnleashtheHounds, 
				ArcaneIntellect, FrostNova, Counterspell, IceBarrier, MirrorEntity, Spellbender, Vaporize, Provoke, Liquor, StaveOff, 
				TouchofKarma, SpiritTether, ShadowMadness, FanofKnives, Headcrack, FarSight, FeralSpirit, LavaBurst, LightningStorm, DrainLife, 
				ShadowBolt, SenseDemons, ShieldBlock, ],
		'4-Cost Spells': [Swipe, Bite, SouloftheForest, MultiShot, Fireball, Polymorph, ConeofCold, DrunkenBoxing, BlessingofKings, Consecration, 
				HammerofWrath, Equality, HolyNova, PowerInfusion, MassDispel, Mindgames, ShadowWordRuin, BladeFlurry, Hex, Hellfire, 
				Shadowflame, MortalStrike, ],
		'5-Cost Spells': [ChaosNova, ForceofNature, Starfall, ExplosiveShot, QuickSip, BlessedChampion, HolyWrath, Righteousness, Assassinate, Bloodlust, 
				BaneofDoom, Brawl, ],
		'6-Cost Spells': [Starfire, Nourish, Blizzard, InnerPeace, RushingJadeWind, AvengingWrath, SiphonSoul, ],
		'7-Cost Spells': [Flamestrike, Sprint, ],
		'8-Cost Spells': [InnerDemon, GiftoftheWild, LayonHands, TwistingNether, ],
		'9-Cost Spells': [],
		'10-Cost Spells': [Pyroblast, MindControl, ],
		'Class Cards except Demon Hunter': [Innervate, Moonfire, Claw, MarkoftheWild, HealingTouch, SavageRoar, WildGrowth, Swipe, Starfire, IronbarkProtector, 
				Savagery, PoweroftheWild, Wrath, MarkofNature, Bite, KeeperoftheGrove, SouloftheForest, DruidoftheClaw, ForceofNature, Starfall, 
				Nourish, AncientofLore, AncientofWar, GiftoftheWild, Cenarius, ],
		'Class Cards except Druid': [ArcaneShot, TimberWolf, Tracking, HuntersMark, AnimalCompanion, KillCommand, Houndmaster, MultiShot, StarvingBuzzard, TundraRhino, 
				BestialWrath, ExplosiveTrap, FreezingTrap, Misdirection, SnakeTrap, Snipe, Flare, ScavengingHyena, DeadlyShot, EaglehornBow, 
				UnleashtheHounds, ExplosiveShot, SavannahHighmane, GladiatorsLongbow, KingKrush, ],
		'Class Cards except Hunter': [ArcaneMissiles, MirrorImage, ArcaneExplosion, Frostbolt, ArcaneIntellect, FrostNova, Fireball, Polymorph, WaterElemental, Flamestrike, 
				TomeofIntellect, Icicle, ManaWyrm, SorcerersApprentice, Counterspell, IceBarrier, MirrorEntity, Spellbender, Vaporize, KirinTorMage, 
				ConeofCold, EtherealArcanist, Blizzard, ArchmageAntonidas, Pyroblast, ],
		'Class Cards except Mage': [Resuscitate, ArchoftheTemple, CanewithaWineGourd, MonksApprentice, ShaohaosProtection, EffusiveMists, SwiftBrewmaster, Provoke, SweepingKickFighter, ShadoPanWuKao, 
				WiseLorewalkerCho, XuentheWhiteTiger_Mutable_1, DefenseTechniqueMaster, Transcendance, PurifyingBrew, Liquor, StaveOff, TouchofKarma, SpiritTether, DrunkenBoxing, 
				OnimaActuary, SpawnofXuen, QuickSip, PawnofShaohao, ShaohaotheEmperor, InnerPeace, LotusHealer, RushingJadeWind, KunLaiSummitZenAlchemist, FistsoftheHeavens, 
				PandariaGuardian, MonkDragonKeeper, ],
		'Class Cards except Monk': [BlessingofMight, HandofProtection, Humility, LightsJustice, HolyLight, BlessingofKings, Consecration, HammerofWrath, TruesilverChampion, GuardianofKings, 
				BlessingofWisdom, EyeforanEye, NobleSacrifice, Redemption, Repentance, ArgentProtector, Equality, AldorPeacekeeper, SwordofJustice, BlessedChampion, 
				HolyWrath, Righteousness, AvengingWrath, LayonHands, TirionFordring, ],
		'Class Cards except Paladin': [PowerWordShield, HolySmite, MindVision, PsychicConjurer, Radiance, ShadowWordDeath, ShadowWordPain, HolyNova, PowerInfusion, MindControl, 
				CircleofHealing, Silence, InnerFire, ScarletSubjugator, KulTiranChaplain, Lightwell, Thoughtsteal, ShadowMadness, Lightspawn, MassDispel, 
				Mindgames, ShadowWordRuin, CabalShadowPriest, TempleEnforcer, NatalieSeline, ],
		'Class Cards except Priest': [Backstab, DeadlyPoison, SinisterStrike, Sap, Shiv, FanofKnives, Plaguebringer, Assassinate, AssassinsBlade, Sprint, 
				Preparation, Shadowstep, Pilfer, Betrayal, ColdBlood, DefiasRingleader, Eviscerate, PatientAssassin, EdwinVanCleef, Headcrack, 
				PerditionsBlade, SI7Agent, BladeFlurry, MasterofDisguise, Kidnapper, ],
		'Class Cards except Rogue': [AncestralHealing, TotemicMight, FrostShock, RockbiterWeapon, Windfury, FlametongueTotem, Hex, Windspeaker, Bloodlust, FireElemental, 
				DustDevil, EarthShock, ForkedLightning, LightningBolt, AncestralSpirit, StormforgedAxe, FarSight, FeralSpirit, LavaBurst, LightningStorm, 
				ManaTideTotem, UnboundElemental, Doomhammer, EarthElemental, AlAkirtheWindlord, ],
		'Class Cards except Shaman': [SacrificialPact, Corruption, MortalCoil, Soulfire, Voidwalker, Felstalker, DrainLife, ShadowBolt, Hellfire, DreadInfernal, 
				BloodImp, CalloftheVoid, FlameImp, Demonfire, SenseDemons, SummoningPortal, Felguard, VoidTerror, PitLord, Shadowflame, 
				BaneofDoom, SiphonSoul, Siegebreaker, TwistingNether, LordJaraxxus, ],
		'Class Cards except Warlock': [Whirlwind, Charge, Execute, Cleave, HeroicStrike, FieryWarAxe, ShieldBlock, WarsongCommander, KorkronElite, ArcaniteReaper, 
				InnerRage, ShieldSlam, Upgrade, Armorsmith, BattleRage, CommandingShout, CruelTaskmaster, Rampage, Slam, FrothingBerserker, 
				ArathiWeaponsmith, MortalStrike, Brawl, Gorehowl, GrommashHellscream, ],
		'Class Cards except Warrior': [ShadowhoofSlayer, ChaosStrike, SightlessWatcher, AldrachiWarblades, CoordinatedStrike, SatyrOverseer, SoulCleave, ChaosNova, GlaiveboundAdept, InnerDemon, 
				],
		'Class Cards except Neutral': [ArcaneShot, TimberWolf, Tracking, HuntersMark, AnimalCompanion, KillCommand, Houndmaster, MultiShot, StarvingBuzzard, TundraRhino, 
				BestialWrath, ExplosiveTrap, FreezingTrap, Misdirection, SnakeTrap, Snipe, Flare, ScavengingHyena, DeadlyShot, EaglehornBow, 
				UnleashtheHounds, ExplosiveShot, SavannahHighmane, GladiatorsLongbow, KingKrush, ],
		'Demons': [ShadowhoofSlayer, SightlessWatcher, SatyrOverseer, Voidwalker, Felstalker, DreadInfernal, Xavius, BloodImp, FlameImp, Felguard, 
				VoidTerror, PitLord, Siegebreaker, LordJaraxxus, ],
		'Demons to Summon': [ShadowhoofSlayer, SightlessWatcher, SatyrOverseer, Voidwalker, Felstalker, DreadInfernal, Xavius, BloodImp, FlameImp, Felguard, 
				VoidTerror, PitLord, Siegebreaker, LordJaraxxus, ],
		}